In [1]:
import sys
sys.path.append('../')
import os
os.environ['PATH'] = os.environ['PATH'] + os.pathsep + '/home/ubuntu/miniconda3/envs/utrtool/bin/'

import pybedtools

from utrcalling import utr_reference as utr_ref

In [2]:
gtf_path = "../tests/test_data/test_mus_musculus_GRCm38_102.gtf"
%time utr = utr_ref.extract_feature(gtf_path, 'three_prime_utr')
print(utr)

2021-06-18 14:37:34,836 - INFO - Parsing GTF reference file to retrieve only the UTR annotations
INFO:root:Extracted GTF attributes: ['gene_id', 'gene_version', 'transcript_id', 'transcript_version', 'exon_number', 'gene_name', 'gene_source', 'gene_biotype', 'havana_gene', 'havana_gene_version', 'transcript_name', 'transcript_source', 'transcript_biotype', 'protein_id', 'protein_version', 'tag', 'transcript_support_level', 'ccds_id', 'exon_id', 'exon_version', 'havana_transcript', 'havana_transcript_version']
2021-06-18 14:37:34,927 - INFO - Finished parsing GTF file
CPU times: user 87 ms, sys: 7.68 ms, total: 94.7 ms
Wall time: 93.2 ms
     seqname          source          feature      start        end  score  \
4          1         ensembl  three_prime_utr  130697017  130697884    NaN
5          1         ensembl  three_prime_utr  170885460  170885881    NaN
6          1         ensembl  three_prime_utr   77367185   77369671    NaN
21         1  ensembl_havana  three_prime_utr   10024601   10024978    NaN
22         1  ensembl_havana  three_prime_utr  128412118  128412347    NaN
...      ...             ...              ...        ...        ...    ...
1991       X          havana  three_prime_utr   71313814   71315265    NaN
1992       X          havana  three_prime_utr   73090951   73090958    NaN
1993       X          havana  three_prime_utr   78449613   78452686    NaN
1994       X          havana  three_prime_utr   95642164   95642165    NaN
1999       Y          havana  three_prime_utr    1224497    1224546    NaN

     strand frame             gene_id gene_version  ...  \
4         -     0  ENSMUSG00000026409           14  ...
5         +     0  ENSMUSG00000096968            1  ...
6         -     0  ENSMUSG00000026235           14  ...
21        -     0  ENSMUSG00000025917            9  ...
22        -     0  ENSMUSG00000026356           15  ...
...     ...   ...                 ...          ...  ...
1991      +     0  ENSMUSG00000031337           16  ...
1992      -     0  ENSMUSG00000057836           12  ...
1993      -     0  ENSMUSG00000047996           16  ...
1994      -     0  ENSMUSG00000035062           13  ...
1999      -     0  ENSMUSG00000068457           14  ...

           transcript_biotype protein_id protein_version         tag  \
4              protein_coding                             CCDS,basic
5              protein_coding                                  basic
6              protein_coding                             CCDS,basic
21             protein_coding                             CCDS,basic
22             protein_coding                             CCDS,basic
...                       ...        ...             ...         ...
1991           protein_coding                                  basic
1992  nonsense_mediated_decay
1993           protein_coding                             CCDS,basic
1994           protein_coding                             CCDS,basic
1999  nonsense_mediated_decay

     transcript_support_level    ccds_id exon_id exon_version  \
4                           1  CCDS35701
5                          NA
6                           1  CCDS35627
21                          1  CCDS14818
22                          1  CCDS48348
...                       ...        ...     ...          ...
1991                        5
1992                        5
1993                        1  CCDS53121
1994                        1  CCDS81154
1999                        1

       havana_transcript havana_transcript_version
4
5
6
21    OTTMUST00000072996                         2
22    OTTMUST00000126318                         1
...                  ...                       ...
1991  OTTMUST00000043170                         1
1992  OTTMUST00000096660                         1
1993  OTTMUST00000043239                         1
1994  OTTMUST00000043647                         1
1999  OTTMUST00000081744                         1

[1032 rows x 30 columns]

In [3]:
feature_list = utr["feature"].unique()
print(feature_list)

['three_prime_utr']

In [4]:
utr['seqname'].unique()

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19',
       '2', '3', '4', '5', '6', '7', '8', '9', 'X', 'Y'], dtype=object)

In [5]:
utr = utr.sort_values(by=['seqname', 'start'])  # sort by chr and start for bed merge
utr.fillna(value={'score': 0}, inplace=True)
print(utr)

     seqname          source          feature      start        end  score  \
100        1          havana  three_prime_utr    7160892    7161063    0.0
107        1          havana  three_prime_utr    9552943    9552976    0.0
108        1          havana  three_prime_utr    9553318    9553472    0.0
21         1  ensembl_havana  three_prime_utr   10024601   10024978    0.0
70         1          havana  three_prime_utr   15843083   15843470    0.0
...      ...             ...              ...        ...        ...    ...
1980       X          havana  three_prime_utr  166189501  166189820    0.0
1981       X          havana  three_prime_utr  167476787  167478076    0.0
1982       X          havana  three_prime_utr  167497813  167497949    0.0
1950       X  ensembl_havana  three_prime_utr  169776378  169776476    0.0
1999       Y          havana  three_prime_utr    1224497    1224546    0.0

     strand frame             gene_id gene_version  ...  \
100       +     0  ENSMUSG00000051285           17  ...
107       +     0  ENSMUSG00000025911           14  ...
108       +     0  ENSMUSG00000025911           14  ...
21        -     0  ENSMUSG00000025917            9  ...
70        +     0  ENSMUSG00000025925           14  ...
...     ...   ...                 ...          ...  ...
1980      +     0  ENSMUSG00000040621           14  ...
1981      -     0  ENSMUSG00000049176           16  ...
1982      -     0  ENSMUSG00000049176           16  ...
1950      -     0  ENSMUSG00000055357            8  ...
1999      -     0  ENSMUSG00000068457           14  ...

           transcript_biotype protein_id protein_version  \
100   nonsense_mediated_decay
107   nonsense_mediated_decay
108   nonsense_mediated_decay
21             protein_coding
70             protein_coding
...                       ...        ...             ...
1980           protein_coding
1981  nonsense_mediated_decay
1982  nonsense_mediated_decay
1950           protein_coding
1999  nonsense_mediated_decay

                             tag transcript_support_level    ccds_id exon_id  \
100   cds_start_NF,mRNA_start_NF                        5
107                                                     3
108                                                     3
21                    CCDS,basic                        1  CCDS14818
70                    CCDS,basic                        1  CCDS78547
...                          ...                      ...        ...     ...
1980                  CCDS,basic                        1  CCDS81195
1981                                                    1
1982                                                    1
1950                       basic                        1
1999                                                    1

     exon_version   havana_transcript havana_transcript_version
100                OTTMUST00000113809                         1
107                OTTMUST00000053150                         2
108                OTTMUST00000053150                         2
21                 OTTMUST00000072996                         2
70                 OTTMUST00000123361                         1
...           ...                 ...                       ...
1980               OTTMUST00000046674                         1
1981               OTTMUST00000046901                         3
1982               OTTMUST00000046901                         3
1950               OTTMUST00000046818                         1
1999               OTTMUST00000081744                         1

[1032 rows x 30 columns]

In [6]:
# ann_remove = ['seqname', 'start', 'end']
annotations = ['gene_id', 'score', 'strand', 'transcript_id']
columns, ann_idx = utr_ref.prepare_annotations_index(annotations)
utr_bed = pybedtools.BedTool.from_dataframe(utr, columns=columns)
utr_bed.saveas('testbed.bed')
utr_reduced = utr_ref.reduce_regions(utr_bed,
annotations_index=ann_idx)  # find and merge overlapping regions

2021-06-18 14:37:35,075 - INFO - Merging overlapping UTR regions

In [7]:
print(utr)

     seqname          source          feature      start        end  score  \
100        1          havana  three_prime_utr    7160892    7161063    0.0
107        1          havana  three_prime_utr    9552943    9552976    0.0
108        1          havana  three_prime_utr    9553318    9553472    0.0
21         1  ensembl_havana  three_prime_utr   10024601   10024978    0.0
70         1          havana  three_prime_utr   15843083   15843470    0.0
...      ...             ...              ...        ...        ...    ...
1980       X          havana  three_prime_utr  166189501  166189820    0.0
1981       X          havana  three_prime_utr  167476787  167478076    0.0
1982       X          havana  three_prime_utr  167497813  167497949    0.0
1950       X  ensembl_havana  three_prime_utr  169776378  169776476    0.0
1999       Y          havana  three_prime_utr    1224497    1224546    0.0

     strand frame             gene_id gene_version  ...  \
100       +     0  ENSMUSG00000051285           17  ...
107       +     0  ENSMUSG00000025911           14  ...
108       +     0  ENSMUSG00000025911           14  ...
21        -     0  ENSMUSG00000025917            9  ...
70        +     0  ENSMUSG00000025925           14  ...
...     ...   ...                 ...          ...  ...
1980      +     0  ENSMUSG00000040621           14  ...
1981      -     0  ENSMUSG00000049176           16  ...
1982      -     0  ENSMUSG00000049176           16  ...
1950      -     0  ENSMUSG00000055357            8  ...
1999      -     0  ENSMUSG00000068457           14  ...

           transcript_biotype protein_id protein_version  \
100   nonsense_mediated_decay
107   nonsense_mediated_decay
108   nonsense_mediated_decay
21             protein_coding
70             protein_coding
...                       ...        ...             ...
1980           protein_coding
1981  nonsense_mediated_decay
1982  nonsense_mediated_decay
1950           protein_coding
1999  nonsense_mediated_decay

                             tag transcript_support_level    ccds_id exon_id  \
100   cds_start_NF,mRNA_start_NF                        5
107                                                     3
108                                                     3
21                    CCDS,basic                        1  CCDS14818
70                    CCDS,basic                        1  CCDS78547
...                          ...                      ...        ...     ...
1980                  CCDS,basic                        1  CCDS81195
1981                                                    1
1982                                                    1
1950                       basic                        1
1999                                                    1

     exon_version   havana_transcript havana_transcript_version
100                OTTMUST00000113809                         1
107                OTTMUST00000053150                         2
108                OTTMUST00000053150                         2
21                 OTTMUST00000072996                         2
70                 OTTMUST00000123361                         1
...           ...                 ...                       ...
1980               OTTMUST00000046674                         1
1981               OTTMUST00000046901                         3
1982               OTTMUST00000046901                         3
1950               OTTMUST00000046818                         1
1999               OTTMUST00000081744                         1

[1032 rows x 30 columns]

In [8]:
print(utr_reduced.head())

1	7160892	7161063	ENSMUSG00000051285	0.0	+	ENSMUST00000182675	1
 1	9552943	9552976	ENSMUSG00000025911	0.0	+	ENSMUST00000130927	1
 1	9553318	9553472	ENSMUSG00000025911	0.0	+	ENSMUST00000130927	1
 1	10024601	10024978	ENSMUSG00000025917	0.0	-	ENSMUST00000027050	1
 1	15843083	15843470	ENSMUSG00000025925	0.0	+	ENSMUST00000027057	1
 1	30944938	30945030	ENSMUSG00000117310	0.0	-	ENSMUST00000233506	1
 1	33734702	33734858	ENSMUSG00000004768	0.0	+	ENSMUST00000138024	1
 1	34552334	34552678	ENSMUSG00000037529	0.0	-	ENSMUST00000190790	1
 1	34811830	34812739	ENSMUSG00000037509	0.0	+	ENSMUST00000159747	1
 1	36428102	36428216	ENSMUSG00000001143	0.0	-	ENSMUST00000001171	1
 None

In [9]:
utr_reduced.saveas('testbed_merged.bed')

In [10]:
from utrcalling import utr_mapping

# check if aligments are correctly parsed: (each should output True)
print(all(alignment.proper_pair for alignment in alignments))
print(not any(alignment.pcr_or_optical_duplicate for alignment in alignments))
print(not any(alignment.not_primary_alignment for alignment in alignments))

In [11]:
intervals = utr_mapping.generate_utr_intervals(utr_reduced)
ct = 0
for name, interval in intervals.items(): 
    print(name, interval, interval.start_d, sep=': ')
    ct += 1
    if ct == 5:
        break

Generating genomic interval for UTR number: 100%|██████████| 1016/1016 [00:00<00:00, 115865.38it/s]ENSMUSG00000051285: 1:[7160891,7161063)/+: 7160891
ENSMUSG00000025911: 1:[9552942,9552976)/+: 9552942
ENSMUSG00000025911_1: 1:[9553317,9553472)/+: 9553317
ENSMUSG00000025917: 1:[10024600,10024978)/-: 10024977
ENSMUSG00000025925: 1:[15843082,15843470)/+: 15843082

In [12]:
print(intervals['ENSMUSG00000005804'], intervals['ENSMUSG00000025917'], sep='\n')

2:[122746630,122749475)/+
1:[10024600,10024978)/-

In [13]:
alignments = ["../tests/test_data/test_UTRoldNSCgenome_bwt2_102_sort.bam", "../tests/test_data/test_UTRyoungNSCgenome_bwt2_102_sort.bam"]
read_mappings = [utr_mapping.map_reads_to_utr(alignment, intervals, read='first', version=2) for alignment in alignments]

2021-06-18 14:37:35,325 - INFO - Extracting reads from ../tests/test_data/test_UTRoldNSCgenome_bwt2_102_sort.bam and mapping them to the reference UTR
Mapping reads to reference UTR number: 100%|██████████| 1016/1016 [00:00<00:00, 5161.19it/s]
2021-06-18 14:37:35,538 - INFO - Size of mapped reads object in bytes: 351752

Memory usage:3.0
2021-06-18 14:37:35,539 - INFO - Extracting reads from ../tests/test_data/test_UTRyoungNSCgenome_bwt2_102_sort.bam and mapping them to the reference UTR
Mapping reads to reference UTR number: 100%|██████████| 1016/1016 [00:00<00:00, 4837.44it/s]
2021-06-18 14:37:35,765 - INFO - Size of mapped reads object in bytes: 388432

Memory usage:3.0

In [14]:
print(read_mappings[0].ENSMUSG00000005804)

MappedReadInformation(utr_name='ENSMUSG00000005804', read_start_positions=[122748098, 122748088, 122748096], read_strands=['-', '-', '-'], read_barcodes=['GATGAAACATTAACCG', 'TGCGCAGAGTCCATAC', 'GCTGGGTGTACGCACC'], read_umis=['CAACACAAG', 'ATCGAGAGT', 'CTGAGTATG'], read_lengths=[51, 37, 44], utr_sizes_from_reads=[1468, 1458, 1466])

In [15]:
dct = read_mappings[0].todict()
for key, value in dct.items():
    print(key, value, sep='\n')
    break

ENSMUSG00000025917
{'utr_name': 'ENSMUSG00000025917', 'read_start_positions': [10024824, 10024829, 10024829, 10024833], 'read_strands': ['+', '+', '+', '+'], 'read_barcodes': ['CGTTGGGCAGTCAGAG', 'CCGTGGAGTCTCGTTC', 'GTAGTCAAGCTATGCT', 'TGCGCAGAGGCATGTG'], 'read_umis': ['TGGCTTATA', 'AACGTAACA', 'ACCTCCGGT', 'ACCCGCACT'], 'read_lengths': [46, 50, 48, 46], 'utr_sizes_from_reads': [153, 148, 148, 144]}

In [16]:
read_mappings[1]['ENSMUSG00000005804', 'ENSMUSG00000025917']

[MappedReadInformation(utr_name='ENSMUSG00000005804', read_start_positions=[122748095, 122748095], read_strands=['-', '-'], read_barcodes=['AGACGTTAGTTGCAGG', 'GGCGACTGTAGCAAAT'], read_umis=['CTCATGGTA', 'ACCGGGTCC'], read_lengths=[44, 43], utr_sizes_from_reads=[1465, 1465]),
 MappedReadInformation(utr_name='ENSMUSG00000025917', read_start_positions=[10024602, 10024826, 10024829, 10024829, 10024835, 10024839], read_strands=['+', '+', '+', '+', '+', '+'], read_barcodes=['CGACCTTTCTGCTGCT', 'TGTTCCGAGGGTCGAT', 'GTACGTAAGCGTTTAC', 'GTGCGGTAGGACAGCT', 'GCTGCAGCACTGTGTA', 'GTCCTCAGTAAACGCG'], read_umis=['TCACGTGAG', 'TCCTAAATG', 'ATGATCGGT', 'TCCAGGAAT', 'TTTAGAACT', 'GCTAGGACG'], read_lengths=[43, 45, 54, 50, 41, 41], utr_sizes_from_reads=[375, 151, 148, 148, 142, 138])]

In [17]:
read_mappings[0][0:4:2]

['ENSMUSG00000025917', 'ENSMUSG00000037509']

In [18]:
from utrcalling import peak_calling

/home/ubuntu/miniconda3/envs/utrtool/lib/python3.9/site-packages/anndata/core/anndata.py:17: FutureWarning: pandas.core.index is deprecated and will be removed in a future version.  The public classes are available in the top-level namespace.
  from pandas.core.index import RangeIndex

In [19]:
positions_counts_merged = peak_calling.merge_samples_utr_sizes(read_mappings)
print(len(positions_counts_merged), positions_counts_merged.ENSMUSG00000025917, sep='\n\n')

2021-06-18 14:37:36,413 - INFO - Merging all samples' UTR sizes
100%|██████████| 2/2 [00:00<00:00, 81.18it/s]71

MappedReadInformation(utr_name='ENSMUSG00000025917', read_start_positions=[10024824, 10024829, 10024829, 10024833, 10024602, 10024826, 10024829, 10024829, 10024835, 10024839], read_strands=['+', '+', '+', '+', '+', '+', '+', '+', '+', '+'], read_barcodes=['CGTTGGGCAGTCAGAG-1', 'CCGTGGAGTCTCGTTC-1', 'GTAGTCAAGCTATGCT-1', 'TGCGCAGAGGCATGTG-1', 'CGACCTTTCTGCTGCT-2', 'TGTTCCGAGGGTCGAT-2', 'GTACGTAAGCGTTTAC-2', 'GTGCGGTAGGACAGCT-2', 'GCTGCAGCACTGTGTA-2', 'GTCCTCAGTAAACGCG-2'], read_umis=['TGGCTTATA', 'AACGTAACA', 'ACCTCCGGT', 'ACCCGCACT', 'TCACGTGAG', 'TCCTAAATG', 'ATGATCGGT', 'TCCAGGAAT', 'TTTAGAACT', 'GCTAGGACG'], read_lengths=[46, 50, 48, 46, 43, 45, 54, 50, 41, 41], utr_sizes_from_reads=[153, 148, 148, 144, 375, 151, 148, 148, 142, 138])

In [20]:
utr_subsetted = peak_calling.subset_reference_data(positions_counts_merged, utr_reduced)
print(f'sizes: subset: {len(utr_subsetted)}, original: {len(utr_reduced)}')

2021-06-18 14:37:36,475 - INFO - Subsetting UTR reference data
sizes: subset: 71, original: 1016

In [21]:
utr_subsetted.iloc[0]

chrom                          1
start                   10024601
end                     10024978
name          ENSMUSG00000025917
score                        0.0
strand                         -
thickStart    ENSMUST00000027050
thickEnd                       1
Name: 0, dtype: object

In [22]:
%time ft = peak_calling.filter_utr_sizes(positions_counts_merged)

2021-06-18 14:37:36,547 - INFO - Filtering samples UTR sizes
CPU times: user 14.6 ms, sys: 0 ns, total: 14.6 ms
Wall time: 14.2 ms

In [23]:
import pandas as pd
vivo_anno_path = "../tests/test_data/vivo_anno.csv"
vivo_anno = pd.read_csv(vivo_anno_path)

In [24]:
vivo_anno.head()

          CellBarcode CellType CellAge      pTime
0  AAACCTGCACCAGTTA-1    qNSC1     old   4.018431
1  AAACCTGCATGGTCAT-1    qNSC2     old  14.861303
2  AAACGGGCACCGGAAA-1    qNSC2     old  20.304435
3  AAACGGGCAGCAGTTT-1    qNSC2     old  10.686136
4  AAACGGGGTAAGTTCC-1    qNSC2     old  10.351203

In [25]:
len(ft)

71

In [26]:
ft.ENSMUSG00000025917

MappedReadInformation(utr_name='ENSMUSG00000025917', read_start_positions=[10024824, 10024829, 10024829, 10024833, 10024602, 10024826, 10024829, 10024829, 10024835, 10024839], read_strands=['+', '+', '+', '+', '+', '+', '+', '+', '+', '+'], read_barcodes=['CGTTGGGCAGTCAGAG-1', 'CCGTGGAGTCTCGTTC-1', 'GTAGTCAAGCTATGCT-1', 'TGCGCAGAGGCATGTG-1', 'CGACCTTTCTGCTGCT-2', 'TGTTCCGAGGGTCGAT-2', 'GTACGTAAGCGTTTAC-2', 'GTGCGGTAGGACAGCT-2', 'GCTGCAGCACTGTGTA-2', 'GTCCTCAGTAAACGCG-2'], read_umis=['TGGCTTATA', 'AACGTAACA', 'ACCTCCGGT', 'ACCCGCACT', 'TCACGTGAG', 'TCCTAAATG', 'ATGATCGGT', 'TCCAGGAAT', 'TTTAGAACT', 'GCTAGGACG'], read_lengths=[46, 50, 48, 46, 43, 45, 54, 50, 41, 41], utr_sizes_from_reads=[153, 148, 148, 144, 375, 151, 148, 148, 142, 138])

In [27]:
counter = 0
control = 0
barcodes_real = vivo_anno.CellBarcode
for barcodes in ft.read_barcodes:
    control +=1
    if set(barcodes).issubset(barcodes_real):
        counter += 1
print(counter, control, sep='\n\n')

32

71

In [28]:
filts = peak_calling.filter_barcodes(ft, vivo_anno_path)
len(filts)

2021-06-18 14:37:36,743 - INFO - Filtering cell barcodes

71

In [29]:
counter = 0
control = 0
barcodes_real = vivo_anno.CellBarcode
for barcodes in filts.read_barcodes:
    control +=1
    if set(barcodes).issubset(barcodes_real):
        counter += 1
print(counter, control, sep='\n\n')

71

71

In [30]:
print(positions_counts_merged.ENSMUSG00000025917, ft.ENSMUSG00000025917, filts.ENSMUSG00000025917, sep='\n\n')

MappedReadInformation(utr_name='ENSMUSG00000025917', read_start_positions=[10024824, 10024829, 10024829, 10024833, 10024602, 10024826, 10024829, 10024829, 10024835, 10024839], read_strands=['+', '+', '+', '+', '+', '+', '+', '+', '+', '+'], read_barcodes=['CGTTGGGCAGTCAGAG-1', 'CCGTGGAGTCTCGTTC-1', 'GTAGTCAAGCTATGCT-1', 'TGCGCAGAGGCATGTG-1', 'CGACCTTTCTGCTGCT-2', 'TGTTCCGAGGGTCGAT-2', 'GTACGTAAGCGTTTAC-2', 'GTGCGGTAGGACAGCT-2', 'GCTGCAGCACTGTGTA-2', 'GTCCTCAGTAAACGCG-2'], read_umis=['TGGCTTATA', 'AACGTAACA', 'ACCTCCGGT', 'ACCCGCACT', 'TCACGTGAG', 'TCCTAAATG', 'ATGATCGGT', 'TCCAGGAAT', 'TTTAGAACT', 'GCTAGGACG'], read_lengths=[46, 50, 48, 46, 43, 45, 54, 50, 41, 41], utr_sizes_from_reads=[153, 148, 148, 144, 375, 151, 148, 148, 142, 138])

MappedReadInformation(utr_name='ENSMUSG00000025917', read_start_positions=[10024824, 10024829, 10024829, 10024833, 10024602, 10024826, 10024829, 10024829, 10024835, 10024839], read_strands=['+', '+', '+', '+', '+', '+', '+', '+', '+', '+'], read_barcodes=['CGTTGGGCAGTCAGAG-1', 'CCGTGGAGTCTCGTTC-1', 'GTAGTCAAGCTATGCT-1', 'TGCGCAGAGGCATGTG-1', 'CGACCTTTCTGCTGCT-2', 'TGTTCCGAGGGTCGAT-2', 'GTACGTAAGCGTTTAC-2', 'GTGCGGTAGGACAGCT-2', 'GCTGCAGCACTGTGTA-2', 'GTCCTCAGTAAACGCG-2'], read_umis=['TGGCTTATA', 'AACGTAACA', 'ACCTCCGGT', 'ACCCGCACT', 'TCACGTGAG', 'TCCTAAATG', 'ATGATCGGT', 'TCCAGGAAT', 'TTTAGAACT', 'GCTAGGACG'], read_lengths=[46, 50, 48, 46, 43, 45, 54, 50, 41, 41], utr_sizes_from_reads=[153, 148, 148, 144, 375, 151, 148, 148, 142, 138])

MappedReadInformation(utr_name='ENSMUSG00000025917', read_start_positions=[10024824, 10024829, 10024833, 10024602, 10024826, 10024829, 10024829, 10024835, 10024839], read_strands=['+', '+', '+', '+', '+', '+', '+', '+', '+'], read_barcodes=['CGTTGGGCAGTCAGAG-1', 'CCGTGGAGTCTCGTTC-1', 'TGCGCAGAGGCATGTG-1', 'CGACCTTTCTGCTGCT-2', 'TGTTCCGAGGGTCGAT-2', 'GTACGTAAGCGTTTAC-2', 'GTGCGGTAGGACAGCT-2', 'GCTGCAGCACTGTGTA-2', 'GTCCTCAGTAAACGCG-2'], read_umis=['TGGCTTATA', 'AACGTAACA', 'ACCCGCACT', 'TCACGTGAG', 'TCCTAAATG', 'ATGATCGGT', 'TCCAGGAAT', 'TTTAGAACT', 'GCTAGGACG'], read_lengths=[46, 50, 46, 43, 45, 54, 50, 41, 41], utr_sizes_from_reads=[153, 148, 144, 375, 151, 148, 148, 142, 138])

In [31]:
print(ft.ENSMUSG00000025917['read_barcodes'], filts.ENSMUSG00000025917['read_barcodes'], sep='\n\n')

['CGTTGGGCAGTCAGAG-1', 'CCGTGGAGTCTCGTTC-1', 'GTAGTCAAGCTATGCT-1', 'TGCGCAGAGGCATGTG-1', 'CGACCTTTCTGCTGCT-2', 'TGTTCCGAGGGTCGAT-2', 'GTACGTAAGCGTTTAC-2', 'GTGCGGTAGGACAGCT-2', 'GCTGCAGCACTGTGTA-2', 'GTCCTCAGTAAACGCG-2']

['CGTTGGGCAGTCAGAG-1', 'CCGTGGAGTCTCGTTC-1', 'TGCGCAGAGGCATGTG-1', 'CGACCTTTCTGCTGCT-2', 'TGTTCCGAGGGTCGAT-2', 'GTACGTAAGCGTTTAC-2', 'GTGCGGTAGGACAGCT-2', 'GCTGCAGCACTGTGTA-2', 'GTCCTCAGTAAACGCG-2']

In [32]:
df, obs, peak_var = peak_calling.generate_peak_counts(filts, annotations=vivo_anno)
print(df)

2021-06-18 14:37:39,590 - INFO - Generating and counting UTR size peaks
Calling peaks for UTR number: 100%|██████████| 71/71 [00:01<00:00, 62.72it/s]                    ENSMUSG00000025917-1  ENSMUSG00000025917-2  \
CGGAGCTAGTATTGGA-2                   0.0                   0.0
GAACGGATCTTTCCTC-1                   0.0                   0.0
CGCGTTTCATCCGTGG-2                   0.0                   0.0
AGGGTGACAGTAAGCG-1                   0.0                   0.0
CCAGCGAGTAGCACGA-2                   0.0                   0.0
...                                  ...                   ...
GGAGCAATCATCGGAT-2                   0.0                   0.0
TCGGTAATCAAAGACA-2                   0.0                   0.0
GAACATCAGTCCCACG-1                   0.0                   0.0
CGTAGGCTCTTGAGGT-2                   0.0                   0.0
AGCTCTCAGGAGTAGA-1                   0.0                   0.0

                    ENSMUSG00000025925-1  ENSMUSG00000037509-1  \
CGGAGCTAGTATTGGA-2                   0.0                   0.0
GAACGGATCTTTCCTC-1                   0.0                   0.0
CGCGTTTCATCCGTGG-2                   0.0                   0.0
AGGGTGACAGTAAGCG-1                   0.0                   0.0
CCAGCGAGTAGCACGA-2                   0.0                   0.0
...                                  ...                   ...
GGAGCAATCATCGGAT-2                   0.0                   0.0
TCGGTAATCAAAGACA-2                   0.0                   0.0
GAACATCAGTCCCACG-1                   0.0                   0.0
CGTAGGCTCTTGAGGT-2                   0.0                   0.0
AGCTCTCAGGAGTAGA-1                   0.0                   0.0

                    ENSMUSG00000026356-1  ENSMUSG00000058267-1  \
CGGAGCTAGTATTGGA-2                   0.0                   0.0
GAACGGATCTTTCCTC-1                   0.0                   0.0
CGCGTTTCATCCGTGG-2                   0.0                   0.0
AGGGTGACAGTAAGCG-1                   0.0                   0.0
CCAGCGAGTAGCACGA-2                   0.0                   0.0
...                                  ...                   ...
GGAGCAATCATCGGAT-2                   0.0                   0.0
TCGGTAATCAAAGACA-2                   0.0                   0.0
GAACATCAGTCCCACG-1                   0.0                   0.0
CGTAGGCTCTTGAGGT-2                   0.0                   0.0
AGCTCTCAGGAGTAGA-1                   0.0                   0.0

                    ENSMUSG00000058267-2  ENSMUSG00000058267-3  \
CGGAGCTAGTATTGGA-2                   0.0                   0.0
GAACGGATCTTTCCTC-1                   0.0                   0.0
CGCGTTTCATCCGTGG-2                   0.0                   0.0
AGGGTGACAGTAAGCG-1                   0.0                   0.0
CCAGCGAGTAGCACGA-2                   0.0                   0.0
...                                  ...                   ...
GGAGCAATCATCGGAT-2                   0.0                   0.0
TCGGTAATCAAAGACA-2                   0.0                   0.0
GAACATCAGTCCCACG-1                   0.0                   0.0
CGTAGGCTCTTGAGGT-2                   0.0                   0.0
AGCTCTCAGGAGTAGA-1                   0.0                   0.0

                    ENSMUSG00000004207-1  ENSMUSG00000020231-1  ...  \
CGGAGCTAGTATTGGA-2                   0.0                   0.0  ...
GAACGGATCTTTCCTC-1                   0.0                   0.0  ...
CGCGTTTCATCCGTGG-2                   0.0                   0.0  ...
AGGGTGACAGTAAGCG-1                   0.0                   0.0  ...
CCAGCGAGTAGCACGA-2                   1.0                   0.0  ...
...                                  ...                   ...  ...
GGAGCAATCATCGGAT-2                   0.0                   0.0  ...
TCGGTAATCAAAGACA-2                   0.0                   0.0  ...
GAACATCAGTCCCACG-1                   0.0                   0.0  ...
CGTAGGCTCTTGAGGT-2                   0.0                   0.0  ...
AGCTCTCAGGAGTAGA-1                   0.0                   0.0  ...

                    ENSMUSG00000032002-1  ENSMUSG00000032002-2  \
CGGAGCTAGTATTGGA-2                   0.0                   0.0
GAACGGATCTTTCCTC-1                   0.0                   0.0
CGCGTTTCATCCGTGG-2                   0.0                   0.0
AGGGTGACAGTAAGCG-1                   0.0                   0.0
CCAGCGAGTAGCACGA-2                   0.0                   0.0
...                                  ...                   ...
GGAGCAATCATCGGAT-2                   0.0                   0.0
TCGGTAATCAAAGACA-2                   0.0                   0.0
GAACATCAGTCCCACG-1                   0.0                   0.0
CGTAGGCTCTTGAGGT-2                   0.0                   0.0
AGCTCTCAGGAGTAGA-1                   0.0                   0.0

                    ENSMUSG00000066892-1  ENSMUSG00000066892-2  \
CGGAGCTAGTATTGGA-2                   0.0                   0.0
GAACGGATCTTTCCTC-1                   0.0                   0.0
CGCGTTTCATCCGTGG-2                   0.0                   0.0
AGGGTGACAGTAAGCG-1                   0.0                   0.0
CCAGCGAGTAGCACGA-2                   0.0                   0.0
...                                  ...                   ...
GGAGCAATCATCGGAT-2                   0.0                   0.0
TCGGTAATCAAAGACA-2                   0.0                   0.0
GAACATCAGTCCCACG-1                   0.0                   0.0
CGTAGGCTCTTGAGGT-2                   0.0                   0.0
AGCTCTCAGGAGTAGA-1                   0.0                   0.0

                    ENSMUSG00000066839-1  ENSMUSG00000066839-2  \
CGGAGCTAGTATTGGA-2                   0.0                   0.0
GAACGGATCTTTCCTC-1                   0.0                   0.0
CGCGTTTCATCCGTGG-2                   0.0                   0.0
AGGGTGACAGTAAGCG-1                   0.0                   0.0
CCAGCGAGTAGCACGA-2                   0.0                   0.0
...                                  ...                   ...
GGAGCAATCATCGGAT-2                   0.0                   0.0
TCGGTAATCAAAGACA-2                   0.0                   0.0
GAACATCAGTCCCACG-1                   0.0                   0.0
CGTAGGCTCTTGAGGT-2                   0.0                   0.0
AGCTCTCAGGAGTAGA-1                   0.0                   0.0

                    ENSMUSG00000034135-1  ENSMUSG00000034135-2  \
CGGAGCTAGTATTGGA-2                   0.0                   0.0
GAACGGATCTTTCCTC-1                   0.0                   0.0
CGCGTTTCATCCGTGG-2                   0.0                   0.0
AGGGTGACAGTAAGCG-1                   0.0                   0.0
CCAGCGAGTAGCACGA-2                   0.0                   0.0
...                                  ...                   ...
GGAGCAATCATCGGAT-2                   0.0                   0.0
TCGGTAATCAAAGACA-2                   0.0                   0.0
GAACATCAGTCCCACG-1                   0.0                   0.0
CGTAGGCTCTTGAGGT-2                   0.0                   0.0
AGCTCTCAGGAGTAGA-1                   0.0                   0.0

                    ENSMUSG00000031429-1  ENSMUSG00000031429-2
CGGAGCTAGTATTGGA-2                   0.0                   0.0
GAACGGATCTTTCCTC-1                   0.0                   0.0
CGCGTTTCATCCGTGG-2                   0.0                   0.0
AGGGTGACAGTAAGCG-1                   0.0                   0.0
CCAGCGAGTAGCACGA-2                   0.0                   0.0
...                                  ...                   ...
GGAGCAATCATCGGAT-2                   0.0                   0.0
TCGGTAATCAAAGACA-2                   0.0                   0.0
GAACATCAGTCCCACG-1                   0.0                   0.0
CGTAGGCTCTTGAGGT-2                   0.0                   0.0
AGCTCTCAGGAGTAGA-1                   0.0                   0.0

[1014 rows x 172 columns]

In [33]:
obs

                   CellType CellAge      pTime
CGGAGCTAGTATTGGA-2    aNSC2   young  22.838630
GAACGGATCTTTCCTC-1    qNSC1     old   1.198426
CGCGTTTCATCCGTGG-2       NB   young  33.109260
AGGGTGACAGTAAGCG-1    qNSC1     old   2.419824
CCAGCGAGTAGCACGA-2    qNSC2   young   5.568644
...                     ...     ...        ...
GGAGCAATCATCGGAT-2    aNSC1   young  21.974728
TCGGTAATCAAAGACA-2      TAP   young  27.531440
GAACATCAGTCCCACG-1    aNSC1     old  20.148197
CGTAGGCTCTTGAGGT-2    qNSC1   young   3.931054
AGCTCTCAGGAGTAGA-1       NB     old  33.066059

[1014 rows x 3 columns]

In [34]:
count_matrix_anndata = peak_calling.generate_count_matrix_anndata(df, obs, peak_var)

2021-06-18 14:37:40,839 - INFO - Generating Count Matrix

In [35]:
print(count_matrix_anndata.var)

                      utr_size
ENSMUSG00000025917-1     149.0
ENSMUSG00000025917-2     375.0
ENSMUSG00000025925-1     346.5
ENSMUSG00000037509-1     906.0
ENSMUSG00000026356-1     226.0
...                        ...
ENSMUSG00000066839-2      76.0
ENSMUSG00000034135-1    1068.0
ENSMUSG00000034135-2    2118.0
ENSMUSG00000031429-1     191.0
ENSMUSG00000031429-2     710.0

[172 rows x 1 columns]

In [36]:
utr_subsetted

,chrom,start,end,name,score,strand,thickStart,thickEnd
0,1,10024601,10024978,ENSMUSG00000025917,0.0,-,ENSMUST00000027050,1
1,1,15843083,15843470,ENSMUSG00000025925,0.0,+,ENSMUST00000027057,1
2,1,34811830,34812739,ENSMUSG00000037509,0.0,+,ENSMUST00000159747,1
3,1,128412118,128412347,ENSMUSG00000026356,0.0,-,ENSMUST00000064309,1
4,1,160199611,160199812,ENSMUSG00000058267,0.0,+,ENSMUST00000097193,1
...,...,...,...,...,...,...,...,...
66,9,7206776,7208205,ENSMUSG00000032002,0.0,+,ENSMUST00000215683,1
67,9,20637786,20638376,ENSMUSG00000066892,0.0,-,"ENSMUST00000086458,ENSMUST00000148631",2
68,9,22072246,22072323,ENSMUSG00000066839,0.0,-,ENSMUST00000098937,1
69,9,46222069,46224194,ENSMUSG00000034135,0.0,+,ENSMUST00000126865,1
70,X,140948429,140949140,ENSMUSG00000031429,0.0,-,ENSMUST00000033805,1

In [37]:
import anndata
peak_counts = anndata.read_h5ad('/home/ubuntu/mytools/utrcalling_/test_utr_results_2.h5ad')

In [38]:
print(f'Counts:\n{peak_counts.X}\n\nObs:\n{peak_counts.obs}\n\nVar:\n{peak_counts.var}')

Counts:
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

Obs:
                    CellType   CellAge      pTime
index
CGGACGTTCGTTGACA-1  b'qNSC1'    b'old'   0.862199
AAACGGGCACCGGAAA-1  b'qNSC2'    b'old'  20.304435
GGGATGACATATGAGA-2    b'TAP'  b'young'  28.605613
GCAATCAGTTAAGAAC-1  b'aNSC2'    b'old'  18.794153
GACGCGTTCTTGAGGT-1     b'NB'    b'old'  32.353067
...                      ...       ...        ...
CGGTTAACAATGAATG-2     b'NB'  b'young'  31.315385
AACTCAGTCTGATTCT-2  b'qNSC2'  b'young'  10.137653
GATCAGTAGACAAAGG-2    b'TAP'  b'young'  31.345172
ATGGGAGCAAAGTGCG-2  b'aNSC1'  b'young'  21.889695
ACATGGTGTCAACATC-1  b'qNSC1'    b'old'  22.241106

[1014 rows x 3 columns]

Var:
                      utr_size
index
ENSMUSG00000025917-1     149.0
ENSMUSG00000025917-2     375.0
ENSMUSG00000025925-1     346.5
ENSMUSG00000037509-1     906.0
ENSMUSG00000026356-1     226.0
...                        ...
ENSMUSG00000066839-2      76.0
ENSMUSG00000034135-1    1068.0
ENSMUSG00000034135-2    2118.0
ENSMUSG00000031429-1     191.0
ENSMUSG00000031429-2     710.0

[172 rows x 1 columns]

In [39]:
positions_counts_merged.__dict__

'AGTATAATA', 'TGTTCCGAT', 'GACTCCCTA', 'GTCGCACGC', 'TAGCCCGAC', 'ATCGGGAAC', 'CTCCGGATT'], read_lengths=[44, 47, 46, 47, 45, 38, 49, 43, 44, 47, 48, 32, 31], utr_sizes_from_reads=[783, 789, 789, 791, 789, 782, 794, 791, 795, 792, 794, 794, 794]),
 'ENSMUSG00000053293': MappedReadInformation(utr_name='ENSMUSG00000053293', read_start_positions=[135376142, 135376141, 135376143, 135376144, 135376146, 135376804, 135376146, 135376146, 135376804, 135376770], read_strands=['-', '+', '+', '+', '+', '-', '+', '+', '-', '+'], read_barcodes=['CTAACTTCATTGAGCT-1', 'GCCAAATTCCATGAAC-1', 'ACACCCTGTTCAGGCC-1', 'GCGGGTTGTCTGCGGT-1', 'TGCCCTACATTTGCTT-1', 'GAAACTCTCTGTACGA-1', 'GCTTGAAAGACTTGAA-2', 'CGAACATAGGCCCTTG-2', 'CGGACACAGAATAGGG-2', 'GAGGTGACAATCCGAT-2'], read_umis=['CTAGCTGGC', 'CCGGACGGA', 'CCCATTGAA', 'TATGGACGC', 'GGAACTTAC', 'TGCCAGAGG', 'CCCTCCGGA', 'CATTGATTA', 'GAGATTTTA', 'TTAAATTGC'], read_lengths=[43, 47, 40, 44, 42, 49, 44, 43, 51, 42], utr_sizes_from_reads=[1933, 1934, 1932, 1931, 1929, 1271, 1929, 1929, 1271, 1305]),
 'ENSMUSG00000037364': MappedReadInformation(utr_name='ENSMUSG00000037364', read_start_positions=[137295715, 137295716, 137295714, 137295716, 137295716, 137295720], read_strands=['+', '+', '+', '+', '+', '+'], read_barcodes=['CCTTACGAGGCGATAC-1', 'CCACCTAAGTTAAGTG-1', 'TGAAAGACACCCATGG-2', 'CTTGGCTGTCCGACGT-2', 'GCTCCTATCAACACGT-2', 'TCTGGAATCTGGCGAC-2'], read_umis=['TCAGTTTAG', 'GGGTCTAGG', 'GAATTAGAC', 'AAATCTGGC', 'TCCAGCCCA', 'CGGATTTGT'], read_lengths=[43, 39, 44, 36, 44, 49], utr_sizes_from_reads=[114, 113, 115, 113, 113, 109]),
 'ENSMUSG00000016510': MappedReadInformation(utr_name='ENSMUSG00000016510', read_start_positions=[146955606, 146955606, 146955606, 146955606, 146955602, 146954934, 146955600, 146955606, 146955604, 146955604, 146955606, 146955606], read_strands=['-', '-', '-', '-', '-', '+', '-', '-', '-', '-', '-', '-'], read_barcodes=['CTCTGGTAGGCTATCT-1', 'CGTCCATTCGGATGGA-1', 'GCATGCGCAGGAATGC-1', 'CCTCAGTAGCTGTCTA-1', 'ACTTTCAAGACTTTCG-1', 'CAGATCAGTACCGGCT-2', 'GTCTCGTGTCACCCAG-2', 'CAGCGACCAGGGTTAG-2', 'GGACGTCAGAGCTTCT-2', 'AGCAGCCGTCCATCCT-2', 'CCCAATCCAATCCAAC-2', 'AGGGATGCAGCTGTGC-2'], read_umis=['AGAAGCTCC', 'TTGGCTTGG', 'GGGTAGTCT', 'ATACTACAT', 'GGCTCGGTG', 'TTCGATCTA', 'CAAGGCTAC', 'CGTTCTCGG', 'TCGCTACGA', 'GCATATCGC', 'CCGTTCCAA', 'ACAGGGGGA'], read_lengths=[47, 46, 44, 44, 40, 48, 46, 50, 48, 47, 47, 37], utr_sizes_from_reads=[14, 14, 14, 14, 10, 658, 8, 14, 12, 12, 14, 14]),
 'ENSMUSG00000053768': MappedReadInformation(utr_name='ENSMUSG00000053768', read_start_positions=[32792218, 32792218, 32792223, 32792224, 32792224, 32792224, 32792224, 32792228, 32792228, 32792229, 32792229, 32792640, 32792224, 32792224, 32792224, 32792228, 32792229, 32792229, 32792287, 32792669], read_strands=['+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+'], read_barcodes=['TCTGAGACATACTACG-1', 'TGATTTCGTTACAGAA-1', 'TGCCCATGTATAGTAG-1', 'CGCTGGATCAGCAACT-1', 'GCAATCAAGCTCTCGG-1', 'GACCAATGTGATGTGG-1', 'CAGGTGCTCGGCATCG-1', 'ACTTGTTGTAGGGTAC-1', 'CAGCATACACTGTGTA-1', 'TTATGCTGTGTCTGAT-1', 'TCGGGACCACGCATCG-1', 'ATCTGCCAGTCGTTTG-1', 'TAAGTGCCAGGTCCAC-2', 'GGGAATGGTTGCCTCT-2', 'AACTGGTCACATAACC-2', 'TAGTTGGCACGCTTTC-2', 'CGTTCTGGTGATGTCT-2', 'AAATGCCCAGTCCTTC-2', 'AGGTCCGCATACAGCT-2', 'TGTTCCGTCAAACCAC-2'], read_umis=['ATATAGCCA', 'CCAACCAAA', 'GAGGCATCA', 'AATACTAGA', 'ATGCAAATA', 'GATCTTGGC', 'AGCCCCATG', 'CTATGACGA', 'AACGAATTC', 'ATAGGCCAT', 'TCCCATCGA', 'GAATAGGTT', 'TTATGTATT', 'CACTACAAG', 'GGTCTAACG', 'AGCTTCATT', 'TTGAATAAT', 'AAGCTAAAT', 'AATCTCGAA', 'TCTGATAGA'], read_lengths=[43, 51, 47, 48, 47, 47, 45, 44, 44, 47, 46, 57, 56, 43, 45, 46, 42, 46, 46, 52], utr_sizes_from_reads=[683, 683, 678, 677, 677, 677, 677, 673, 673, 672, 672, 261, 677, 677, 677, 673, 672, 672, 614, 232]),
 'ENSMUSG00000014554': MappedReadInformation(utr_name='ENSMUSG00000014554', read_start_positions=[83480216, 83480216], read_strands=['+', '+'], read_barcodes=['CAGCTGGGTCCTGCTT-1', 'TACTTGTCAGATAATG-2'], read_umis=['CTGCGCGTA', 'AAGAACAGC'], read_lengths=[50, 55], utr_sizes_from_reads=[1245, 1245]),
 'ENSMUSG00000034192': MappedReadInformation(utr_name='ENSMUSG00000034192', read_start_positions=[91522621, 91522618, 91522619, 91522619, 91522621, 91522621, 91522619, 91522621, 91522621, 91522619, 91522624, 91522622, 91522624, 91522621, 91522619, 91522619, 91522621, 91522617, 91522614, 91522618, 91522618, 91522619, 91522620, 91522619, 91522619, 91522621, 91522619, 91522620, 91522619, 91522620, 91522624, 91522618, 91522619, 91522621, 91522621, 91522621, 91522624, 91522621, 91522618, 91522624, 91522620, 91522620, 91522624], read_strands=['-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-'], read_barcodes=['CGAATGTCATGCCTTC-1', 'TGATTTCGTGCGCTTG-1', 'ACGATGTGTCAATACC-1', 'ACGATGTGTCAATACC-1', 'GTGCTTCCATGACGGA-1', 'CTGCCTAAGACAGACC-1', 'CCAATCCCAGCGAACA-1', 'AGCCTAAGTTCAGCGC-1', 'CCATGTCAGAGCTGCA-1', 'TCGCGAGCATGGGACA-1', 'ATCGAGTGTATATGGA-1', 'CACCAGGTCAGCTGGC-1', 'CGTTCTGAGAATTGTG-1', 'CGACCTTCATCTGGTA-1', 'CGTCCATTCTTGGGTA-1', 'ACGAGCCCAAGTCTAC-1', 'AAAGCAATCAATCACG-1', 'GGTGCGTTCTATCCCG-2', 'CCGTACTTCTCATTCA-2', 'CTCTACGGTCTCCACT-2', 'TGCCCTACACTCTGTC-2', 'AGTTGGTTCGAGAACG-2', 'AAAGATGTCTGGCGAC-2', 'CCAATCCTCGGCTACG-2', 'CGAACATTCATGCATG-2', 'CCCTCCTAGTTATCGC-2', 'ACTGAACGTCCGAAGA-2', 'CGTTGGGTCCATGCTC-2', 'TCGTAGATCACTATTC-2', 'GCGCAGTAGGAATCGC-2', 'GAATGAAAGAAGGACA-2', 'AACTTTCAGTAGTGCG-2', 'TCAGATGGTGTGAAAT-2', 'CGACTTCTCTTCCTTC-2', 'TACCTTAAGGCGTACA-2', 'AGGTCCGAGCTCTCGG-2', 'GCTCCTAAGTATTGGA-2', 'TCAGCTCTCTCTAGGA-2', 'CGCTTCATCTACTTAC-2', 'TTTACTGGTTTGACTG-2', 'GGACAAGCAGATTGCT-2', 'GCACTCTGTTCACCTC-2', 'AACTCCCAGTATTGGA-2'], read_umis=['GACTTAGAT', 'ATGGTCGTA', 'AAAACACAG', 'CGATTTAGG', 'CTCAATTGC', 'TCGGATATA', 'AATGAAGAT', 'GTACAAGAT', 'CCGCCTGGT', 'CTACTCTTC', 'AACGAATTA', 'GCGAAATGG', 'TACTCGTAA', 'TTATCCGTA', 'AATAAGGCA', 'CTTCTATGC', 'TCGAGGAGA', 'TAACAGGCC', 'ATAGGACAA', 'TTACCGCGA', 'AGGCGCAAC', 'TCCTAAGCA', 'CCAACTGTC', 'GGTTACCGG', 'CATAGTGCC', 'AAGTCAGGG', 'GTAGGCCAG', 'AACATTGTC', 'TGCTCGATT', 'AACTCATTC', 'AAAATTGGC', 'CAGAAGCCA', 'CTATAGTCT', 'AGCTAGTAA', 'TCATAGGAG', 'TACGATTGA', 'TGTTGGTCA', 'CCAGCGGCA', 'TAATGCGGC', 'GGACTCCCT', 'CCTCGTAAG', 'CGTGCTCGG', 'GGGTTTAGT'], read_lengths=[49, 46, 46, 45, 47, 46, 44, 45, 45, 43, 47, 44, 45, 41, 39, 37, 39, 47, 43, 47, 47, 48, 48, 45, 45, 47, 45, 46, 45, 46, 50, 44, 44, 46, 46, 46, 49, 43, 39, 45, 40, 40, 43], utr_sizes_from_reads=[300, 297, 298, 298, 300, 300, 298, 300, 300, 298, 303, 301, 303, 300, 298, 298, 300, 296, 293, 297, 297, 298, 299, 298, 298, 300, 298, 299, 298, 299, 303, 297, 298, 300, 300, 300, 303, 300, 297, 303, 299, 299, 303]),
 'ENSMUSG00000030400': MappedReadInformation(utr_name='ENSMUSG00000030400', read_start_positions=[19395693, 19395692], read_strands=['-', '-'], read_barcodes=['CCTACACGTCCCTTGT-1', 'AGCTTGAAGGCATGGT-2'], read_umis=['AGCAGCCAA', 'GGCACGGTG'], read_lengths=[47, 41], utr_sizes_from_reads=[1249, 1248]),
 'ENSMUSG00000054793': MappedReadInformation(utr_name='ENSMUSG00000054793', read_start_positions=[24504534, 24504531, 24504536, 24504450, 24504537], read_strands=['-', '-', '-', '-', '-'], read_barcodes=['ACCCACTAGAGCTGCA-1', 'GCAATCAAGACTCGGA-1', 'GTCTTCGAGATCCCAT-1', 'GAAATGATCTCCAGGG-2', 'AGCAGCCGTCCATCCT-2'], read_umis=['CGCACAAAC', 'TTAGGCACG', 'GTAAACTCA', 'AGGAGACCC', 'ATTGGTTAT'], read_lengths=[49, 43, 42, 55, 52], utr_sizes_from_reads=[913, 910, 915, 829, 916]),
 'ENSMUSG00000030591': MappedReadInformation(utr_name='ENSMUSG00000030591', read_start_positions=[29174187, 29174253, 29174253, 29174253, 29174254, 29174254, 29174255, 29174255, 29174256, 29174256, 29174256, 29174466, 29174528, 29174530, 29174531, 29174533, 29174188, 29174189, 29174189, 29174255, 29174256, 29174256, 29174256, 29174257, 29174258], read_strands=['+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+'], read_barcodes=['GTGCATAAGCAGCCTC-1', 'GCAGCCAAGAGCTATA-1', 'AGGCCACGTGAGGCTA-1', 'TGGCGCATCGGATGGA-1', 'CAGCATACACTGTGTA-1', 'GTACGTACATGGTCAT-1', 'TTTGGTTTCATCTGCC-1', 'AACCATGTCTGTTTGT-1', 'CGAGCCAGTGCCTTGG-1', 'GTGGGTCCAGTCGATT-1', 'TACGGGCAGCTGCAAG-1', 'AGAGTGGTCTTAGCCC-1', 'CGCGGTACACTTAACG-1', 'GCAGCCAAGAGCTATA-1', 'GACACGCCACCAGGTC-1', 'GTGGGTCGTCAAAGAT-1', 'ATGGGAGCAGGCAGTA-2', 'AGCCTAATCTACCTGC-2', 'TAGACCAGTGGTTTCA-2', 'AGCGGTCGTTGCGTTA-2', 'AGCAGCCTCTGCTGCT-2', 'ATGCGATCATTCGACA-2', 'GATTCAGGTTGGTTTG-2', 'CGACTTCTCAGTTGAC-2', 'TGTTCCGAGGGTCGAT-2'], read_umis=['ACCAATGTC', 'CCATGCAAA', 'CGTTCAGAA', 'TCCCATGGA', 'TTCCTGAGA', 'ACAGCGCAC', 'CTTGACACG', 'TCAATTCTA', 'TGTCCATCA', 'TAGGAGGAT', 'TAGTAGGTA', 'ACTCGCAGG', 'TCCACTAAG', 'CCCGCCAGA', 'ATGTACCAT', 'CCTCCCCTG', 'CGGCTGATA', 'TGCTCTGGA', 'GGTGGAAAA', 'GGCACTCCA', 'CCTCTGGAT', 'CCAACATCA', 'TGCAGGCAG', 'CACGGTGGT', 'CTTAGGGAG'], read_lengths=[43, 47, 43, 44, 43, 42, 42, 44, 46, 50, 44, 47, 44, 43, 53, 42, 47, 46, 41, 44, 45, 48, 44, 47, 42], utr_sizes_from_reads=[421, 355, 355, 355, 354, 354, 353, 353, 352, 352, 352, 142, 80, 78, 77, 75, 420, 419, 419, 353, 352, 352, 352, 351, 350]),
 'ENSMUSG00000045411': MappedReadInformation(utr_name='ENSMUSG00000045411', read_start_positions=[44251587, 44252311, 44252316, 44252304, 44252310, 44252313, 44252318, 44252309, 44252318], read_strands=['-', '-', '-', '-', '-', '-', '-', '-', '-'], read_barcodes=['TCATTACTCCAAACAC-1', 'TTTGGTTGTTGAGTTC-1', 'ATCACGATCCTTTCGG-1', 'CACTCCATCAGAAATG-1', 'GACGTTATCGAGCCCA-1', 'TGGGCGTTCTATGTGG-1', 'GAATGAATCCTTTCGG-1', 'CGACTTCAGATTACCC-2', 'AAGACCTAGTACTTGC-2'], read_umis=['CACCGTTAT', 'GCGCGCCGA', 'CACACCTAA', 'ACGTTCTAG', 'CGACGCCCA', 'CACCTTACC', 'CCAATTCAG', 'ATATTTGCA', 'GCCAGGAAA'], read_lengths=[45, 50, 52, 38, 44, 44, 45, 43, 49], utr_sizes_from_reads=[60, 784, 789, 777, 783, 786, 791, 782, 791]),
 'ENSMUSG00000030452': MappedReadInformation(utr_name='ENSMUSG00000030452', read_start_positions=[55931272, 55931273, 55931284, 55931285, 55932557, 55932567, 55931288, 55932499, 55932557, 55932620], read_strands=['+', '+', '+', '+', '+', '+', '+', '+', '+', '+'], read_barcodes=['CATCAAGCAAGCCGTC-1', 'AACTCCCCATATACCG-1', 'CGGACACGTCTCTCGT-1', 'TGAAAGAGTATCGCAT-1', 'ACGAGGATCATGGTCA-1', 'CCTTCCCAGTCGCCGT-1', 'GCAAACTGTTCAGTAC-2', 'GGATTACCATGACATC-2', 'GGGCACTTCGTCTGAA-2', 'ACCAGTACAAAGGAAG-2'], read_umis=['TGCTAAATG', 'GAAGAAATA', 'ATGGGTACC', 'CTATCCCCG', 'TTTGGAGGA', 'CATCCCCGC', 'TCAAGCCGG', 'GTACACTAA', 'CCCGTTTAA', 'CGTAATAAG'], read_lengths=[42, 46, 54, 43, 39, 42, 45, 48, 48, 51], utr_sizes_from_reads=[1642, 1641, 1630, 1629, 357, 347, 1626, 415, 357, 294]),
 'ENSMUSG00000030701': MappedReadInformation(utr_name='ENSMUSG00000030701', read_start_positions=[100643895, 100643898, 100643899, 100643898, 100643900, 100643900], read_strands=['+', '+', '+', '+', '+', '+'], read_barcodes=['GATCGTAAGTAGCGGT-1', 'GTGAAGGGTTTGACTG-1', 'ATTGGACAGGCTAGCA-1', 'AGCTCTCGTATATGGA-2', 'ACACCAAAGCTGTCTA-2', 'GCTCCTAGTCCGCTGA-2'], read_umis=['ACAACAGCA', 'ATTCCAATA', 'AAGACCATA', 'GCATTGCCT', 'CCTCATAGA', 'ACCGCTGGC'], read_lengths=[51, 48, 44, 49, 43, 42], utr_sizes_from_reads=[1036, 1033, 1032, 1033, 1031, 1031]),
 'ENSMUSG00000030982': MappedReadInformation(utr_name='ENSMUSG00000030982', read_start_positions=[118841486, 118841485, 118841486], read_strands=['-', '-', '-'], read_barcodes=['ACCCACTGTCTAGGTT-1', 'ATCTGCCCATAAGACA-1', 'TCTGGAATCCAGTATG-2'], read_umis=['TCGGGCAAT', 'CGGAAAGTT', 'CCGCACTCA'], read_lengths=[44, 42, 40], utr_sizes_from_reads=[192, 191, 192]),
 'ENSMUSG00000030695': MappedReadInformation(utr_name='ENSMUSG00000030695', read_start_positions=[126795233, 126795233, 126795233, 126795233, 126795233, 126795233, 126795234, 126795235, 126795235, 126795235, 126795235, 126795236, 126795236, 126795236, 126795236, 126795236, 126795243, 126795243, 126795244, 126795233, 126795233, 126795233, 126795233, 126795233, 126795233, 126795235, 126795235, 126795235, 126795235, 126795241, 126795244, 126795244], read_strands=['+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+'], read_barcodes=['TGGTTCCCACATCCAA-1', 'GCATACACAAGCGATG-1', 'GTTTCTAGTGTCGCTG-1', 'AGGGTGACAGTAAGCG-1', 'GTTCGGGCATGAGCGA-1', 'GTGCATAAGCAGCCTC-1', 'AAGACCTAGCTAGTCT-1', 'AAAGCAAGTTCCACAA-1', 'AACCGCGAGCACCGTC-1', 'AAAGTAGCAGCGAACA-1', 'CCTAAAGTCTACTTAC-1', 'CCTTACGGTAAATGAC-1', 'TCAGCTCCACTTGGAT-1', 'TGTGGTACAATTGCTG-1', 'CTCAGAAAGACCACGA-1', 'TGAGGGATCGTTGACA-1', 'TGCGCAGCACAGACTT-1', 'GTAGTCACAGTAGACC-1', 'ACGCAGCAGTCGATAA-1', 'AACTCCCAGTCCAGGA-2', 'CGGAGCTCACTAAGTC-2', 'CCGTGGACAGGTGGAT-2', 'CGATGTAAGAGGTTAT-2', 'TTTGTCACATCATCCC-2', 'TTTACTGTCTCTGAGA-2', 'GTGCATATCATCACCC-2', 'ACATGGTAGAGACTAT-2', 'ACTTGTTCATCTCGCT-2', 'ATGGGAGAGAGGGATA-2', 'TCGGGACTCCCAACGG-2', 'TGCTACCTCTCAAACG-2', 'CTACCCATCTACTCAT-2'], read_umis=['AGAATTAGC', 'CAGAGCTCA', 'TTTAGGTGG', 'ATTATCGTT', 'ACACCTTAG', 'CTCTGAGAT', 'TAATATACC', 'GCGGCCTAT', 'TTAATAACA', 'CGGTGACTA', 'AGCGCAAAC', 'ACACAACAG', 'TGCACCAGC', 'CTAAAGTTT', 'CCGCCCGCA', 'GTGTCGGTG', 'TGCGTTTCC', 'GGTCGCATA', 'TGAAAGGTA', 'CAATTACAG', 'TTGGTCGGT', 'TCTGGCTTT', 'ATTGGCAAT', 'ACCTTTGAG', 'AAGCCTTAA', 'GACGGACGC', 'GGTGGCCCG', 'CGTACGGTC', 'AGCCACCTG', 'TGGTTTTCA', 'TCAAACGAC', 'ACAGAATGC'], read_lengths=[52, 46, 52, 54, 45, 41, 44, 47, 46, 47, 48, 46, 49, 47, 48, 49, 44, 51, 45, 49, 49, 48, 49, 36, 40, 46, 47, 39, 43, 45, 43, 48], utr_sizes_from_reads=[184, 184, 184, 184, 184, 184, 183, 182, 182, 182, 182, 181, 181, 181, 181, 181, 174, 174, 173, 184, 184, 184, 184, 184, 184, 182, 182, 182, 182, 176, 173, 173]),
 'ENSMUSG00000054716': MappedReadInformation(utr_name='ENSMUSG00000054716', read_start_positions=[127254801, 127254798, 127254799, 127254805, 127254804, 127254801], read_strands=['-', '-', '-', '-', '-', '-'], read_barcodes=['CCCATACGTTCATGGT-1', 'TTATGCTGTTAAGTAG-1', 'TTATGCTAGACTGTAA-1', 'CTAGAGTGTTAAGGGC-1', 'GATGAGGCAGTCCTTC-1', 'GTACGTAAGCGTTTAC-2'], read_umis=['GCCCTGGGT', 'TGCAGCCAA', 'CCAATCGGG', 'TGTCAAAAA', 'GCCTTATCA', 'TCCACTAGT'], read_lengths=[52, 46, 41, 45, 42, 48], utr_sizes_from_reads=[184, 181, 182, 188, 187, 184]),
 'ENSMUSG00000030822': MappedReadInformation(utr_name='ENSMUSG00000030822', read_start_positions=[127476759, 127476757], read_strands=['-', '-'], read_barcodes=['CCGGTAGCACTCTGTC-1', 'AGCTCCTTCGTTTATC-2'], read_umis=['GTATGTATC', 'CCAAAATAG'], read_lengths=[45, 44], utr_sizes_from_reads=[99, 97]),
 'ENSMUSG00000038416': MappedReadInformation(utr_name='ENSMUSG00000038416', read_start_positions=[13781878, 13781924, 13781937, 13781934], read_strands=['-', '-', '-', '-'], read_barcodes=['TCTGGAACAATAACGA-1', 'TATCAGGAGGCATGTG-1', 'CCAATCCAGTGTACGG-1', 'CCGTACTAGACTTGAA-2'], read_umis=['CGCTTGGAT', 'TTCGGAGCA', 'TCATTACGG', 'AAAAGCTAA'], read_lengths=[43, 42, 49, 48], utr_sizes_from_reads=[247, 293, 306, 303]),
 'ENSMUSG00000070003': MappedReadInformation(utr_name='ENSMUSG00000070003', read_start_positions=[70597492, 70597492, 70597489, 70597489, 70597489, 70597492], read_strands=['+', '+', '+', '+', '+', '+'], read_barcodes=['TCAATCTAGGCTAGCA-1', 'CTGATCCTCGTTTAGG-1', 'ACAGCTAAGACCTAGG-2', 'ATCGAGTTCACGCGGT-2', 'TGGCCAGAGTGTTGAA-2', 'CAGCATAGTATCAGTC-2'], read_umis=['ATCCGCAGG', 'AATTGGCGA', 'ATGCCACTA', 'GAGTGCCTA', 'GAGTAGATA', 'TGAATTAAC'], read_lengths=[44, 42, 43, 45, 47, 43], utr_sizes_from_reads=[417, 417, 420, 420, 420, 417]),
 'ENSMUSG00000036672': MappedReadInformation(utr_name='ENSMUSG00000036672', read_start_positions=[105844668, 105844672, 105844678, 105844675, 105844675], read_strands=['+', '+', '+', '+', '+'], read_barcodes=['GCTGCTTCAGTATAAG-1', 'CTAATGGTCGTTTGCC-1', 'CCACCTAAGTTAAGTG-1', 'AAGTCTGTCTCGTATT-2', 'ACCCACTTCTCTGCTG-2'], read_umis=['CCCCAAGCA', 'TTGGGCGAT', 'TGGCATGTA', 'GTTAACGTA', 'GGTATCTGA'], read_lengths=[54, 53, 47, 50, 47], utr_sizes_from_reads=[326, 322, 316, 319, 319]),
 'ENSMUSG00000036270': MappedReadInformation(utr_name='ENSMUSG00000036270', read_start_positions=[105893207, 105893207, 105893207], read_strands=['-', '-', '-'], read_barcodes=['ACCTTTAGTCCGAATT-1', 'CACTCCAGTCATCGGC-1', 'CTACACCTCCACGACG-2'], read_umis=['TCACCCCAC', 'CCCGTGAAG', 'AGCCCTGTT'], read_lengths=[53, 47, 59], utr_sizes_from_reads=[345, 345, 345]),
 'ENSMUSG00000032002': MappedReadInformation(utr_name='ENSMUSG00000032002', read_start_positions=[7207021, 7207020, 7207027, 7207021, 7207021, 7207022, 7207027, 7207030, 7207027, 7207026, 7207022, 7207027, 7207028, 7207036, 7207037, 7207041, 7207041, 7207037, 7207053, 7208203, 7207022, 7207027, 7207027, 7207029, 7207027, 7207028, 7207029, 7207036, 7207036, 7207030, 7207037, 7207037], read_strands=['-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-'], read_barcodes=['GGTGAAGCATGGTCAT-1', 'ACCAGTATCGTCTGCT-1', 'CTGGTCTTCTGCGACG-1', 'CTGCGGAGTCTAGAGG-1', 'CTACATTAGATTACCC-1', 'ATCCGAATCAAGATCC-1', 'CTTACCGAGGGTCTCC-1', 'TCTCTAAGTAACGACG-1', 'CCTATTACACATTTCT-1', 'CTCGTACCACCGAATT-1', 'TAGGCATAGCTGGAAC-1', 'ATAACGCTCGCGTAGC-1', 'ACTGCTCCAGTATGCT-1', 'GTGCATACACCATCCT-1', 'CTAACTTAGGTGCAAC-1', 'AACTCAGGTGCGATAG-1', 'CTCGAAACATTACGAC-1', 'TTGCCGTCATCTCGCT-1', 'TGAAAGAAGGCTCATT-1', 'CATCCACAGCCACCTG-1', 'ACTTTCACACAGCCCA-2', 'TTAGGACAGATGTCGG-2', 'CGATCGGCAAGCCCAC-2', 'CAGATCAGTACCGGCT-2', 'CCCTCCTAGTTATCGC-2', 'AGAGCTTTCCCTAACC-2', 'ATCTACTTCGGTTCGG-2', 'ACCGTAAGTACAGTGG-2', 'GGGTCTGTCACAGGCC-2', 'CTACATTTCCGTACAA-2', 'TACGGATGTCATCGGC-2', 'TCACAAGTCTGGCGAC-2'], read_umis=['CACGGTGAG', 'GGTCCCGCC', 'GCAGCGATA', 'AGGAATCTA', 'CGAGCAATA', 'CGTCTGAGC', 'ACTTAAGGG', 'TTTGCCCCA', 'CATTATGGA', 'TACAGTGGG', 'CTGCACAAG', 'GTGGCCCGC', 'TGTGCCTTC', 'ATTGTAGTT', 'GTAGTACCT', 'GTCACATGC', 'TGCCCAGAT', 'GTTAACACA', 'GACTCATCA', 'TTCGCTCGG', 'ATAACGCCT', 'ACGAAAATC', 'GGTCTAGAA', 'CAGACACTT', 'CCTTTGGGG', 'TATTGAATG', 'CCTCATCAA', 'CGCCTGCAG', 'GCTATAGAA', 'ACTACATGT', 'CAATTGCGA', 'GAAGGTAAA'], read_lengths=[48, 46, 52, 45, 45, 44, 47, 50, 47, 45, 41, 45, 45, 46, 46, 46, 45, 40, 40, 47, 47, 52, 47, 49, 47, 46, 45, 51, 49, 42, 44, 41], utr_sizes_from_reads=[246, 245, 252, 246, 246, 247, 252, 255, 252, 251, 247, 252, 253, 261, 262, 266, 266, 262, 278, 1428, 247, 252, 252, 254, 252, 253, 254, 261, 261, 255, 262, 262]),
 'ENSMUSG00000066892': MappedReadInformation(utr_name='ENSMUSG00000066892', read_start_positions=[20637785, 20637788, 20637789], read_strands=['+', '+', '+'], read_barcodes=['TCAGGTAGTTAGATGA-1', 'CTACACCCATTCCTCG-1', 'ATGGGAGCACTTCTGC-2'], read_umis=['GAAACGCCA', 'TTAACCCCA', 'TCCGATCAA'], read_lengths=[49, 47, 45], utr_sizes_from_reads=[590, 587, 586]),
 'ENSMUSG00000066839': MappedReadInformation(utr_name='ENSMUSG00000066839', read_start_positions=[22072246, 22072247, 22072251], read_strands=['+', '+', '+'], read_barcodes=['TAAACCGTCGGAGCAA-1', 'GAATAAGGTGATGTCT-1', 'GCGCAGTAGCTGAAAT-2'], read_umis=['TAGGGGCAT', 'GAATTGGTA', 'TCCAGGAGG'], read_lengths=[43, 44, 43], utr_sizes_from_reads=[76, 75, 71]),
 'ENSMUSG00000034135': MappedReadInformation(utr_name='ENSMUSG00000034135', read_start_positions=[46223138, 46224184, 46224182], read_strands=['-', '-', '-'], read_barcodes=['GTCCTCATCACTTACT-1', 'CCAGCGAAGTAACCCT-1', 'GGGTCTGCAATGACCT-2'], read_umis=['GCCAATTAG', 'TGGAATCCC', 'CTAAAACCA'], read_lengths=[55, 41, 40], utr_sizes_from_reads=[1070, 2116, 2114]),
 'ENSMUSG00000031429': MappedReadInformation(utr_name='ENSMUSG00000031429', read_start_positions=[140948944, 140948430, 140948943, 140948946, 140948947], read_strands=['+', '+', '+', '+', '+'], read_barcodes=['TGTCCCAGTCTAGCCG-1', 'CGCTTCATCTACTTAC-2', 'GGTGCGTTCTATCCCG-2', 'GATTCAGGTTGGTTTG-2', 'TTTGCGCCAGCTATTG-2'], read_umis=['CACATAGGC', 'TTAATAGAG', 'GCACTGCAG', 'CTTGAGTCA', 'GTATTCTTT'], read_lengths=[48, 44, 44, 43, 45], utr_sizes_from_reads=[195, 709, 196, 193, 192])}