In [1]:
import sys
sys.path.append('../')
import os
os.environ['PATH'] = os.environ['PATH'] + os.pathsep + '/home/ubuntu/miniconda3/envs/utrtool/bin/'

import pickle as pkl
import pandas as pd

In [3]:
with open("/mnt/weird_vol/projects/3utr/blood_test/data_inhouse/210708_NB551305_0384_AH2NLFAFX3/utrcalling/intermediate/UTR_sizes_counts_1.pkl", "rb") as input_file:
    counts_1 = pkl.load(input_file)

In [4]:
counts_1.head(n=3)

['ENSG00000188976', 'ENSG00000187961_5', 'ENSG00000187583']

In [6]:
counts_1.ENSG00000188976

MappedReadInformation(utr_name='ENSG00000188976', read_start_positions=[944237, 944236, 944239, 944243, 944237, 944240, 944242, 944246, 944245, 944244, 944243, 944246, 944247, 944247, 944244, 944247, 944245, 944248, 944248, 944251, 944248, 944252, 944248, 944248, 944248, 944249, 944250, 944250, 944252, 944248, 944251, 944250, 944249, 944257, 944250, 944253, 944253, 944255, 944255], read_strands=['+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+'], read_barcodes=['AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302'], read_umis=['GTCGGCAG', 'GGTGTCTC', 'GGTAAAAC', 'GTACCACG', 'CGCGGGCA', 'GCCCAGAC', 'GGCCGATG', 'CCGGGTCA', 'GCAGTCTA', 'TACATCAA', 'TTTGAGGT', 'GCCGCGAA', 'GATCGGTC', 'GTAAGGGG', 'CAGTTTGA', 'CCTGAGTC', 'GTAGTGTA', 'GCCGATCC', 'GGGCAGCG', 'TTGATGCC', 'CTAACTAG', 'CCAAATTG', 'GTAGCCGG', 'TAAAACAG', 'GCTTAGGG', 'CAAGTTAA', 'CGAGGGTG', 'GGGCTGTG', 'ACCAGCGC', 'ATACTATG', 'GGGGGGCC', 'AGGATCAG', 'AACGCTTG', 'TGTCCCAG', 'GGTGCGCG', 'TCTGTAGC', 'TTCCTGTC', 'TTGACTTA', 'CAGGGGGA'], read_lengths=[45, 45, 45, 41, 48, 45, 42, 42, 46, 47, 46, 45, 45, 45, 49, 45, 48, 46, 42, 43, 46, 42, 47, 47, 47, 46, 45, 45, 43, 47, 45, 46, 48, 40, 47, 44, 44, 43, 44], utr_sizes_from_reads=[455, 456, 453, 449, 455, 452, 450, 446, 447, 448, 449, 446, 445, 445, 448, 445, 447, 444, 444, 441, 444, 440, 444, 444, 444, 443, 442, 442, 440, 444, 441, 442, 443, 435, 442, 439, 439, 437, 437])

In [2]:
with open("/mnt/weird_vol/projects/3utr/Blood/14Jan/220114_NB551305_0417_AHY3JTBGXK/utrcalling/intermediate/UTR_sizes_counts_merged_intercept.pkl", "rb") as input_file:
    counts_test = pkl.load(input_file)

In [6]:
with open("/mnt/weird_vol/projects/3utr/blood_test/data_inhouse/210708_NB551305_0384_AH2NLFAFX3/utrcalling/intermediate/UTR_sizes_counts_merged_intercept.pkl", "rb") as input_file:
    counts_previous = pkl.load(input_file)

In [3]:
counts_test.head(n=3)

['ENSG00000187608', 'ENSG00000160087', 'ENSG00000127054']

In [7]:
counts_previous.head(n=3)

['ENSG00000187961_5', 'ENSG00000187608', 'ENSG00000131591']

In [5]:
counts_test.ENSG00000187608

MappedReadInformation(utr_name='ENSG00000187608', read_start_positions=[1014538, 1014538, 1014539, 1014538, 1014538, 1014538, 1014539, 1014534, 1014528, 1014538, 1014539, 1014539, 1014535, 1014538, 1014538, 1014539, 1014538, 1014531, 1014539, 1014539, 1014538, 1014539, 1014533, 1014533, 1014537, 1014539, 1014538, 1014539, 1014533, 1014534, 1014536, 1014539, 1014539, 1014539, 1014535, 1014538, 1014538, 1014537, 1014535, 1014538, 1014537, 1014538, 1014531, 1014537, 1014534, 1014532, 1014535, 1014533, 1014530, 1014539, 1014539, 1014539, 1014539, 1014538, 1014538, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014538, 1014539, 1014539, 1014539, 1014538, 1014537, 1014539, 1014538, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014538, 1014539, 1014538, 1014538, 1014538, 1014539, 1014539, 1014539, 1014538, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014538, 1014539, 1014525, 1014539, 1014538, 1014539, 1014539, 1014538, 1014538, 1014538, 1014539, 1014538, 1014539, 1014539, 1014539, 1014539, 1014538, 1014539, 1014539, 1014539, 1014538, 1014539, 1014534, 1014538, 1014539, 1014539, 1014539, 1014539, 1014539, 1014538, 1014538, 1014539, 1014538, 1014539, 1014539, 1014539, 1014538, 1014538, 1014539, 1014538, 1014538, 1014538, 1014538, 1014539, 1014538, 1014539, 1014539, 1014538, 1014538, 1014538, 1014538, 1014539, 1014538, 1014538, 1014538, 1014539, 1014538, 1014537, 1014529, 1014539, 1014539, 1014539, 1014538, 1014538, 1014538, 1014539, 1014539, 1014539, 1014539, 1014538, 1014538, 1014539, 1014538, 1014539, 1014538, 1014530, 1014538, 1014539, 1014538, 1014538, 1014536, 1014537, 1014539, 1014538, 1014538, 1014538, 1014538, 1014539, 1014539, 1014539, 1014539, 1014537, 1014539, 1014538, 1014539, 1014539, 1014530, 1014539, 1014538, 1014539, 1014539, 1014539, 1014538, 1014539, 1014538, 1014536, 1014539, 1014532, 1014539, 1014539, 1014532, 1014539, 1014533, 1014539, 1014538, 1014539, 1014539, 1014539, 1014539, 1014536, 1014538, 1014539, 1014538, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014538, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014530, 1014539, 1014539, 1014539, 1014539, 1014539, 1014538, 1014538, 1014538, 1014538, 1014539, 1014539, 1014531, 1014539, 1014539, 1014539, 1014538, 1014538, 1014539, 1014538, 1014539, 1014538, 1014533, 1014538, 1014539, 1014539, 1014539, 1014538, 1014539, 1014539, 1014533, 1014539, 1014538, 1014538, 1014523, 1014539, 1014529, 1014538, 1014538, 1014539, 1014533, 1014539, 1014538, 1014533, 1014531, 1014533, 1014539, 1014538, 1014538, 1014539, 1014539, 1014539, 1014532, 1014530, 1014539, 1014532, 1014538, 1014539, 1014539, 1014538, 1014539, 1014538, 1014538, 1014538, 1014539, 1014538, 1014538, 1014539, 1014539, 1014539, 1014538, 1014539, 1014530, 1014539, 1014538, 1014533, 1014539, 1014538, 1014539, 1014539, 1014538, 1014539, 1014539, 1014538, 1014539, 1014538, 1014539, 1014539, 1014537, 1014539, 1014539, 1014538, 1014538, 1014537, 1014539, 1014538, 1014532, 1014518, 1014532, 1014539, 1014536, 1014527, 1014538, 1014538, 1014538, 1014538, 1014538, 1014534, 1014539, 1014534, 1014538, 1014538, 1014538, 1014538, 1014538, 1014539, 1014538, 1014537, 1014533, 1014539, 1014531, 1014536, 1014539, 1014527, 1014539, 1014539, 1014538, 1014523, 1014532, 1014539, 1014538, 1014538, 1014532, 1014532, 1014533, 1014539, 1014539, 1014538, 1014533, 1014539, 1014532, 1014533, 1014539, 1014538, 1014539, 1014533, 1014536, 1014538, 1014538, 1014539, 1014538, 1014538, 1014533, 1014538, 1014539, 1014539, 1014539, 1014536, 1014538, 1014539, 1014538, 1014538, 1014539, 1014536, 1014538, 1014535, 1014533, 1014539, 1014531, 1014537, 1014538, 1014538, 1014539, 1014539, 1014539, 1014534, 1014539, 1014539, 1014536, 1014539, 1014539, 1014532, 1014532, 1014532, 1014538, 1014534, 1014539, 1014538, 1014539, 1014538, 1014536, 1014521, 1014537, 1014538, 1014538, 1014521, 1014538, 1014538, 1014538, 1014538, 1014538, 1014538, 1014532, 1014536, 1014539, 1014537, 1014538, 1014533, 1014538, 1014538, 1014538, 1014538, 1014533, 1014533, 1014538, 1014538, 1014513, 1014522, 1014538, 1014538, 1014537, 1014532, 1014534, 1014538, 1014535, 1014538, 1014531, 1014531, 1014538, 1014531, 1014536, 1014539, 1014532, 1014538, 1014531, 1014538, 1014537, 1014530, 1014531, 1014534, 1014531, 1014533, 1014538, 1014538, 1014526, 1014527, 1014538, 1014534, 1014532, 1014539, 1014534, 1014529, 1014532, 1014526, 1014539, 1014537, 1014523, 1014533, 1014530, 1014529, 1014525, 1014538, 1014525, 1014530, 1014539, 1014524, 1014539, 1014525, 1014524, 1014525, 1014523, 1014518, 1014518, 1014505, 1014511, 1014515, 1014512, 1014496, 1014509, 1014502, 1014516, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014538, 1014526, 1014539, 1014538, 1014539, 1014538, 1014538, 1014539, 1014539, 1014538, 1014538, 1014538, 1014538, 1014539, 1014538, 1014539, 1014538, 1014539, 1014537, 1014539, 1014539, 1014538, 1014539, 1014539, 1014528, 1014539, 1014539, 1014538, 1014539, 1014538, 1014533, 1014536, 1014538, 1014538, 1014532, 1014538, 1014538, 1014533, 1014535, 1014539, 1014539, 1014538, 1014539, 1014538, 1014533, 1014537, 1014538, 1014539, 1014533, 1014530, 1014538, 1014526, 1014535, 1014533, 1014532, 1014535, 1014531, 1014538, 1014529, 1014538, 1014538, 1014538, 1014534, 1014529, 1014526, 1014524, 1014515, 1014507, 1014539, 1014538, 1014539, 1014539, 1014539, 1014538, 1014538, 1014539, 1014539, 1014539, 1014539, 1014538, 1014539, 1014539, 1014538, 1014538, 1014538, 1014538, 1014538, 1014539, 1014539, 1014536, 1014538, 1014539, 1014534, 1014539, 1014539, 1014533, 1014538, 1014538, 1014533, 1014539, 1014539, 1014532, 1014539, 1014538, 1014539, 1014539, 1014537, 1014532, 1014532, 1014538, 1014534, 1014535, 1014537, 1014537, 1014530, 1014538, 1014532, 1014535, 1014532, 1014536, 1014530, 1014538, 1014533, 1014539, 1014534, 1014538, 1014538, 1014538, 1014538, 1014539, 1014538, 1014539, 1014539, 1014530, 1014532, 1014528, 1014538, 1014538, 1014534, 1014531, 1014534, 1014529, 1014538, 1014539, 1014539, 1014539, 1014539, 1014539, 1014538, 1014539, 1014539, 1014539, 1014538, 1014539, 1014533, 1014538, 1014538, 1014531, 1014539, 1014538, 1014533, 1014536, 1014530, 1014538, 1014509, 1014539, 1014538, 1014538, 1014539, 1014538, 1014538, 1014539, 1014539, 1014538, 1014539, 1014538, 1014538, 1014539, 1014538, 1014533, 1014531, 1014538, 1014538, 1014529, 1014498, 1014538, 1014539, 1014539, 1014533, 1014539, 1014539, 1014533, 1014535, 1014538, 1014539, 1014525, 1014536, 1014538, 1014539, 1014539, 1014539, 1014538, 1014539, 1014538, 1014539, 1014539, 1014539, 1014538, 1014538, 1014537, 1014539, 1014539, 1014538, 1014539, 1014539, 1014539, 1014539, 1014538, 1014539, 1014539, 1014531, 1014539, 1014539, 1014538, 1014539, 1014537, 1014539, 1014538, 1014539, 1014538, 1014538, 1014538, 1014539, 1014539, 1014539, 1014539, 1014539, 1014538, 1014538, 1014539, 1014538, 1014538, 1014538, 1014538, 1014538, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014538, 1014539, 1014539, 1014538, 1014535, 1014539, 1014538, 1014538, 1014528, 1014538, 1014539, 1014539, 1014539, 1014538, 1014538, 1014539, 1014539, 1014538, 1014539, 1014538, 1014539, 1014539, 1014528, 1014539, 1014538, 1014538, 1014539, 1014537, 1014538, 1014539, 1014539, 1014539, 1014538, 1014539, 1014539, 1014538, 1014539, 1014534, 1014538, 1014539, 1014534, 1014539, 1014533, 1014539, 1014536, 1014539, 1014535, 1014539, 1014539, 1014539, 1014538, 1014538, 1014539, 1014539, 1014536, 1014538, 1014539, 1014539, 1014535, 1014539, 1014539, 1014539, 1014539, 1014539, 1014538, 1014538, 1014539, 1014538, 1014536, 1014539, 1014538, 1014539, 1014538, 1014539, 1014538, 1014539, 1014539, 1014538, 1014538, 1014538, 1014531, 1014538, 1014538, 1014532, 1014539, 1014538, 1014538, 1014538, 1014538, 1014539, 1014539, 1014539, 1014539, 1014539, 1014538, 1014539, 1014539, 1014538, 1014538, 1014539, 1014538, 1014539, 1014538, 1014538, 1014538, 1014539, 1014538, 1014534, 1014539, 1014532, 1014539, 1014539, 1014532, 1014538, 1014539, 1014538, 1014539, 1014533, 1014538, 1014536, 1014538, 1014539, 1014539, 1014527, 1014538, 1014538, 1014539, 1014536, 1014538, 1014538, 1014538, 1014533, 1014539, 1014538, 1014539, 1014539, 1014539, 1014539, 1014538, 1014539, 1014538, 1014538, 1014538, 1014539, 1014538, 1014539, 1014537, 1014538, 1014539, 1014539, 1014532, 1014536, 1014538, 1014536, 1014534, 1014530, 1014537, 1014538, 1014539, 1014538, 1014533, 1014539, 1014538, 1014538, 1014538, 1014538, 1014536, 1014539, 1014538, 1014533, 1014538, 1014539, 1014538, 1014538, 1014538, 1014539, 1014532, 1014538, 1014539, 1014533, 1014538, 1014538, 1014539, 1014539, 1014538, 1014539, 1014538, 1014538, 1014539, 1014529, 1014539, 1014538, 1014539, 1014538, 1014536, 1014538, 1014532, 1014539, 1014539, 1014537, 1014538, 1014539, 1014539, 1014535, 1014538, 1014539, 1014538, 1014539, 1014539, 1014538, 1014533, 1014538, 1014539, 1014538, 1014536, 1014538, 1014539, 1014538, 1014539, 1014539, 1014539, 1014539, 1014536, 1014539, 1014531, 1014538, 1014538, 1014539, 1014538, 1014533, 1014539, 1014534, 1014539, 1014538, 1014538, 1014539, 1014539, 1014537, 1014539, 1014534, 1014538, 1014538, 1014538, 1014536, 1014539, 1014538, 1014539, 1014538, 1014539, 1014538, 1014538, 1014538, 1014536, 1014538, 1014523, 1014538, 1014523, 1014539, 1014539, 1014535, 1014539, 1014538, 1014539, 1014539, 1014538, 1014539, 1014539, 1014539, 1014538, 1014537, 1014539, 1014539, 1014538, 1014537, 1014539, 1014538, 1014538, 1014539, 1014534, 1014538, 1014534, 1014535, 1014534, 1014538, 1014536, 1014539, 1014538, 1014539, 1014537, 1014535, 1014533, 1014539, 1014537, 1014539, 1014538, 1014538, 1014533, 1014539, 1014534, 1014533, 1014537, 1014535, 1014533, 1014532, 1014538, 1014538, 1014532, 1014531, 1014532, 1014538, 1014532, 1014538, 1014522, 1014534, 1014536, 1014538, 1014528, 1014533, 1014530, 1014538, 1014534, 1014538, 1014531, 1014538, 1014536, 1014535, 1014530, 1014536, 1014538, 1014531, 1014532, 1014531, 1014530, 1014537, 1014532, 1014531, 1014538, 1014534, 1014534, 1014538, 1014533, 1014537, 1014531, 1014538, 1014531, 1014531, 1014529, 1014538, 1014528, 1014531, 1014535, 1014531, 1014534, 1014538, 1014537, 1014538, 1014538, 1014538, 1014531, 1014532, 1014538, 1014526, 1014528, 1014531, 1014538, 1014538, 1014537, 1014531, 1014538, 1014536, 1014531, 1014538, 1014535, 1014531, 1014538, 1014528, 1014528, 1014538, 1014535, 1014537, 1014530, 1014539, 1014531, 1014530, 1014539, 1014538, 1014539, 1014538, 1014529, 1014529, 1014539, 1014528, 1014536, 1014537, 1014527, 1014527, 1014527, 1014531, 1014526, 1014525, 1014531, 1014523, 1014539, 1014520, 1014510, 1014507, 1014539, 1014524, 1014539, 1014538, 1014539, 1014539, 1014538, 1014533, 1014530, 1014539, 1014538, 1014539, 1014538, 1014539, 1014539, 1014536, 1014538, 1014538, 1014538, 1014539, 1014531, 1014534, 1014538, 1014538, 1014496, 1014539, 1014539, 1014539, 1014536, 1014539, 1014539, 1014532, 1014539, 1014529, 1014538, 1014533, 1014538, 1014538, 1014538, 1014538, 1014539, 1014539, 1014539, 1014537, 1014539, 1014539, 1014539, 1014539, 1014532, 1014531, 1014536, 1014520, 1014539, 1014539, 1014538, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014532, 1014538, 1014531, 1014538, 1014538, 1014538, 1014538, 1014539, 1014538, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014538, 1014531, 1014531, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014538, 1014538, 1014539, 1014534, 1014538, 1014539, 1014539, 1014539, 1014532, 1014539, 1014538, 1014539, 1014538, 1014537, 1014539, 1014537, 1014538, 1014538, 1014539, 1014539, 1014539, 1014537, 1014538, 1014539, 1014539, 1014539, 1014538, 1014539, 1014539, 1014539, 1014539, 1014539, 1014538, 1014536, 1014539, 1014533, 1014538, 1014539, 1014532, 1014539, 1014539, 1014538, 1014539, 1014539, 1014538, 1014538, 1014539, 1014533, 1014538, 1014538, 1014538, 1014532, 1014538, 1014538, 1014539, 1014539, 1014538, 1014532, 1014532, 1014538, 1014539, 1014535, 1014532, 1014539, 1014532, 1014538, 1014538, 1014538, 1014538, 1014533, 1014532, 1014538, 1014538, 1014539, 1014539, 1014530, 1014539, 1014533, 1014537, 1014531, 1014539, 1014538, 1014538, 1014539, 1014534, 1014534, 1014538, 1014531, 1014537, 1014538, 1014537, 1014531, 1014530, 1014531, 1014536, 1014537, 1014532, 1014531, 1014538, 1014532, 1014538, 1014539, 1014535, 1014538, 1014528, 1014531, 1014523, 1014503, 1014510, 1014538, 1014538, 1014539, 1014539, 1014539, 1014538, 1014538, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014538, 1014538, 1014535, 1014538, 1014535, 1014538, 1014535, 1014539, 1014539, 1014538, 1014539, 1014531, 1014539, 1014537, 1014538, 1014530, 1014537, 1014538, 1014539, 1014536, 1014536, 1014533, 1014539, 1014529, 1014538, 1014537, 1014533, 1014531, 1014534, 1014538, 1014531, 1014531, 1014531, 1014532, 1014539, 1014530], read_strands=['-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', 

In [9]:
counts_previous.ENSG00000187608

MappedReadInformation(utr_name='ENSG00000187608', read_start_positions=[1014539, 1014538, 1014538, 1014539, 1014538, 1014539, 1014539, 1014538, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014531, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014536, 1014539, 1014539, 1014536, 1014538, 1014532, 1014536, 1014532, 1014539, 1014539, 1014539, 1014539, 1014539, 1014538, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014533, 1014533, 1014532, 1014539, 1014539, 1014539, 1014539, 1014533, 1014539, 1014539, 1014533, 1014539, 1014539, 1014539, 1014536, 1014533, 1014533, 1014539, 1014532, 1014539, 1014539, 1014539, 1014539, 1014538, 1014533, 1014539, 1014539, 1014533, 1014539, 1014539, 1014532, 1014533, 1014539, 1014539, 1014539, 1014539, 1014535, 1014533, 1014539, 1014536, 1014539, 1014533, 1014539, 1014539, 1014537, 1014539, 1014539, 1014533, 1014535, 1014538, 1014534, 1014538, 1014539, 1014539, 1014536, 1014533, 1014534, 1014538, 1014538, 1014538, 1014537, 1014539, 1014539, 1014539, 1014539, 1014539, 1014538, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014538, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014538, 1014539, 1014539, 1014539, 1014536, 1014539, 1014538, 1014539, 1014539, 1014539, 1014532, 1014533, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014536, 1014538, 1014539, 1014539, 1014538, 1014539, 1014539, 1014532, 1014539, 1014539, 1014533, 1014539, 1014538, 1014539, 1014536, 1014539, 1014539, 1014538, 1014538, 1014539, 1014539, 1014539, 1014533, 1014539, 1014533, 1014539, 1014539, 1014539, 1014533, 1014539, 1014533, 1014533, 1014538, 1014533, 1014539, 1014539, 1014538, 1014539, 1014539, 1014533, 1014539, 1014533, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014532, 1014539, 1014539, 1014539, 1014533, 1014533, 1014539, 1014539, 1014536, 1014539, 1014538, 1014533, 1014539, 1014533, 1014539, 1014533, 1014539, 1014539, 1014538, 1014539, 1014539, 1014539, 1014538, 1014539, 1014532, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014533, 1014539, 1014539, 1014539, 1014539, 1014539, 1014538, 1014539, 1014539, 1014533, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014533, 1014539, 1014539, 1014539, 1014539, 1014539, 1014532, 1014539, 1014536, 1014538, 1014539, 1014539, 1014534, 1014539, 1014539, 1014534, 1014539, 1014539, 1014536, 1014535, 1014539, 1014537, 1014535, 1014538, 1014538, 1014538, 1014538, 1014533, 1014538, 1014539, 1014539, 1014538, 1014538, 1014532, 1014538, 1014538, 1014533, 1014537, 1014533, 1014530, 1014539, 1014539, 1014538, 1014539, 1014538, 1014537, 1014539, 1014533, 1014539, 1014539, 1014536, 1014528, 1014533, 1014539, 1014539, 1014539, 1014539, 1014536, 1014534, 1014539, 1014534, 1014533, 1014539, 1014533, 1014533, 1014539, 1014539, 1014539, 1014533, 1014528, 1014534, 1014539, 1014539, 1014539, 1014539, 1014532, 1014538, 1014538, 1014538, 1014536, 1014539, 1014539, 1014539, 1014536, 1014539, 1014538, 1014539, 1014539, 1014533, 1014539, 1014539, 1014539, 1014534, 1014539, 1014538, 1014539, 1014539, 1014538, 1014539, 1014539, 1014532, 1014538, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014538, 1014536, 1014539, 1014539, 1014539, 1014538, 1014537, 1014538, 1014533, 1014537, 1014539, 1014538, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014538, 1014539, 1014534, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014536, 1014539, 1014539, 1014532, 1014539, 1014539, 1014533, 1014532, 1014536, 1014539, 1014539, 1014539, 1014537, 1014539, 1014539, 1014539, 1014539, 1014539, 1014533, 1014538, 1014539, 1014539, 1014539, 1014533, 1014539, 1014539, 1014539, 1014539, 1014539, 1014533, 1014539, 1014539, 1014539, 1014539, 1014533, 1014539, 1014539, 1014538, 1014537, 1014539, 1014533, 1014533, 1014533, 1014539, 1014539, 1014533, 1014533, 1014532, 1014538, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014533, 1014538, 1014539, 1014539, 1014539, 1014539, 1014539, 1014533, 1014539, 1014533, 1014531, 1014539, 1014539, 1014534, 1014539, 1014533, 1014539, 1014538, 1014539, 1014533, 1014539, 1014539, 1014536, 1014539, 1014539, 1014538, 1014539, 1014539, 1014530, 1014539, 1014538, 1014534, 1014533, 1014536, 1014532, 1014538, 1014536, 1014538, 1014538, 1014538, 1014539, 1014539, 1014539, 1014539, 1014539, 1014533, 1014536, 1014538, 1014537, 1014539, 1014529, 1014527, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014538, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014533, 1014532, 1014539, 1014539, 1014533, 1014539, 1014538, 1014539, 1014539, 1014538, 1014539, 1014539, 1014539, 1014539, 1014539, 1014538, 1014533, 1014539, 1014539, 1014539, 1014532, 1014533, 1014532, 1014539, 1014539, 1014532, 1014538, 1014539, 1014539, 1014539, 1014539, 1014533, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014536, 1014533, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014533, 1014533, 1014533, 1014532, 1014533, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014533, 1014539, 1014538, 1014533, 1014539, 1014539, 1014537, 1014530, 1014539, 1014539, 1014534, 1014539, 1014539, 1014537, 1014539, 1014539, 1014538, 1014530, 1014538, 1014536, 1014538, 1014539, 1014538, 1014538, 1014539, 1014538, 1014539, 1014540, 1014540, 1014522, 1014539, 1014539, 1014538, 1014538, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014538, 1014538, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014536, 1014539, 1014539, 1014532, 1014539, 1014539, 1014539, 1014536, 1014539, 1014539, 1014534, 1014538, 1014539, 1014539, 1014539, 1014539, 1014539, 1014537, 1014530, 1014539, 1014539, 1014539, 1014538, 1014539, 1014539, 1014539, 1014537, 1014539, 1014538, 1014539, 1014539, 1014536, 1014539, 1014536, 1014538, 1014539, 1014539, 1014533, 1014533, 1014539, 1014533, 1014539, 1014536, 1014539, 1014539, 1014536, 1014539, 1014538, 1014533, 1014539, 1014536, 1014534, 1014539, 1014539, 1014533, 1014536, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014533, 1014539, 1014539, 1014533, 1014539, 1014539, 1014538, 1014538, 1014539, 1014539, 1014539, 1014539, 1014539, 1014534, 1014534, 1014539, 1014539, 1014533, 1014539, 1014539, 1014539, 1014538, 1014539, 1014539, 1014531, 1014539, 1014527, 1014539, 1014539, 1014539, 1014539, 1014539, 1014538, 1014535, 1014539, 1014539, 1014539, 1014539, 1014539, 1014535, 1014533, 1014537, 1014539, 1014535, 1014537, 1014533, 1014532, 1014538, 1014538, 1014538, 1014538, 1014536, 1014538, 1014530, 1014539, 1014539, 1014538, 1014529, 1014535, 1014532, 1014536, 1014537, 1014539, 1014534, 1014539, 1014539, 1014537, 1014539, 1014526, 1014527, 1014539, 1014539, 1014539, 1014539, 1014533, 1014536, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014533, 1014533, 1014538, 1014539, 1014532, 1014535, 1014539, 1014538, 1014538, 1014536, 1014539, 1014538, 1014535, 1014539, 1014533, 1014539, 1014532, 1014539, 1014539, 1014539, 1014539, 1014539, 1014534, 1014539, 1014539, 1014539, 1014533, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014536, 1014533, 1014539, 1014539, 1014539, 1014534, 1014539, 1014532, 1014539, 1014539, 1014539, 1014538, 1014538, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014537, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014539, 1014538, 1014538, 1014533, 1014533, 1014538, 1014539, 1014538, 1014537, 1014538, 1014538, 1014539, 1014539, 1014539, 1014539, 1014529, 1014529, 1014539, 1014539, 1014537, 1014539, 1014539, 1014532, 1014539, 1014539, 1014539, 1014532, 1014535, 1014539, 1014532, 1014533, 1014539, 1014533, 1014533, 1014539, 1014538, 1014532, 1014534, 1014534, 1014532, 1014538], read_strands=['-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-'], read_barcodes=['AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648850-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-57302', 'AS-648858-LR-573

In [11]:
print(len(wt_test), len(wt_test)/5, sep='\n')

22190
4438.0

In [12]:
wt_test[wt_test[0:2]]

[MappedReadInformation(utr_name='ENSMUSG00000051951', read_start_positions=[3214887, 3215475, 3215548, 3214855, 3214930, 3215118, 3215476, 3215475, 3215506, 3215515, 3215520, 3215530, 3214902, 3215287, 3215280, 3215492, 3215480, 3215491, 3215505, 3215498, 3215501, 3215511, 3215517, 3215515, 3215529, 3214765, 3214765, 3214862, 3214861, 3214872, 3215143, 3215431, 3215519, 3215508, 3215510, 3215513, 3215519, 3215522, 3215528, 3215526, 3215523, 3215550, 3215705, 3214613, 3214654, 3214654, 3214654, 3214864, 3214859, 3214863, 3214872, 3215158, 3215175, 3215499, 3215501, 3215505, 3215508, 3215498, 3215508, 3215505, 3215523, 3215503, 3215504, 3215494, 3215520, 3215514, 3215521, 3215516, 3215519, 3215518, 3215518, 3215523, 3215521, 3215524, 3215816], read_strands=['+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+'], read_barcodes=['TCAGCTCCACTGAAGG-1', 'AAGCCGCGTGAAGGCT-2', 'GGACATTAGAAGAAGC-2', 'CTTAGGACACCTCAGG-3', 'AGGTGTTTCCTTCAGC-3', 'TTCTTGACAGCTGCCA-3', 'GACTTCCAGCTATCTG-3', 'TGACAGTTCTTACGGA-3', 'ATTCCCGCACTTCATT-3', 'ACGTACAAGTACTGGG-3', 'ACGTACAAGTACTGGG-3', 'CGGGCATAGCCTTTCC-3', 'GCACGTGGTGACTCGC-4', 'AATGAAGCAGACCCGT-4', 'CATCCCATCAAAGGAT-4', 'TCCTCTTAGTGGTTAA-4', 'TTCATTGAGTCATTGC-4', 'TTCATTGAGTCATTGC-4', 'CTGCTCAAGCAAGTCG-4', 'ATTCCCGAGATTTGCC-4', 'GGGTATTCAGTTAAAG-4', 'GTCAAACCAATTTCGG-4', 'CGCATAATCACCGCTT-4', 'TGACAGTAGATTTGCC-4', 'TACTTGTGTCAAGGCA-4', 'AATGAAGTCCGCGAGT-5', 'TGCGACGTCGGTAGAG-5', 'TATTGGGCAGAGATGC-5', 'ACGGTTACAGAGACTG-5', 'ANGGTTACAGAGACTG-5', 'ATCACTTGTGGCACTC-5', 'AGGAAATCACTAGTAC-5', 'ATCACTTGTCTGCCTT-5', 'GGTGAAGCACAGCCAC-5', 'TTCCAATCAGTATGAA-5', 'TCTGGCTTCACCTACC-5', 'AACGGGAGTTTACCTT-5', 'CTCTCGATCGCTGTCT-5', 'GTGGTTATCAGTGATC-5', 'TTAATCCAGCACTCCG-5', 'ATGATCGCAGTGTGCC-5', 'GACATCAGTTAAACCC-5', 'CAAAACTTAGTAAAAC-5', 'GACTCTCTCACAGTGT-6', 'TCAAGCAGTCGAATTC-6', 'TCAAGCAGTCGAATTC-6', 'TCAAGCAGTCGAATTC-6', 'CTGCAGGGTTAGAAAC-6', 'GCAGGCTAGCGAACTG-6', 'ACACTGATCCGAAATC-6', 'AAGACAATCTAGCCAA-6', 'CCATAAGTCGGTATGT-6', 'CTTCTCTTCTGCAGCG-6', 'TCCACGTGTGGCCTCA-6', 'AGACAGGTCGACATCA-6', 'AAGTACCCACATTCTT-6', 'CTCCGATGTGTCATCA-6', 'ACTTAGGGTTACACAC-6', 'TGTGGCGCAGTTCCAA-6', 'GTTCGCTCAATGTCAC-6', 'CCTTTGGTCTACGCAA-6', 'TCATTCAGTCCGGACT-6', 'TCCTCGAGTTAGTCGT-6', 'GTGTCCTAGTGGCCTC-6', 'TCTACCGCACCTGCAG-6', 'AGCCAATAGCTACGTT-6', 'AGCCAATAGCTACGTT-6', 'AATCACGTCCAGCTCT-6', 'CTTGAGAAGTCAGAGC-6', 'TATCCTACATCGAGCC-6', 'TCCACCACAGACTCTA-6', 'TCTATACCAAGTATAG-6', 'ACAAGCTGTAGTCCTA-6', 'ATGATCGCAGTGTGCC-6', 'CAACAGTCATCCCACT-6'], read_umis=['GAGGGGACAC', 'TAGCCCAGTC', 'TCTTATGATC', 'AACCCTCTGT', 'TTAATTAAAG', 'TAATTTCTCA', 'AGGCGAATGC', 'CGCTATGAAG', 'ATCGTTATGT', 'TTCCACTGGG', 'GGTGAGTTCA', 'GTTGTCAACT', 'GCGTGTATTT', 'AGTAGTAGAT', 'ATGACCCTCT', 'AAGTCGATGA', 'GAGGCACGTA', 'TATTTTGCAC', 'CCTTTTTATG', 'TCATCCACTG', 'GTAAGGCGAT', 'TGGGTTTCTA', 'TTTCTCGACT', 'ACCTTCAATG', 'TGCAATATCA', 'GTGATTCGTA', 'TTACCTCAGC', 'CCGGACCTTT', 'TGGACGGCTC', 'TGGACGGCTC', 'ATTTGCTTTA', 'CACAGATCTG', 'TACTGATCTA', 'CCAGACACTC', 'TTCTGTCTAG', 'CGAAAGTATA', 'CTTTGGCTAG', 'TAACATCAGG', 'AGTTTCGTAG', 'CTTGGACAAG', 'GAGTATGTAC', 'TTGGCCAAAA', 'CCATCAAAAT', 'TCAGTACCAC', 'TATTTCAGTC', 'TAATCTTCTA', 'CCAACTTTAA', 'CCCAAAATAA', 'TTGTAGATTA', 'ACACGCTATC', 'GATAATCATT', 'TAATTCTTTT', 'TTCCTAACTT', 'AAATTCCGAT', 'ACTTTTCCCC', 'TTGAAAAGGG', 'TCCAAACCGT', 'GAGACGCATG', 'CCTTTCGTGC', 'TCGCGCTGGG', 'TTATCTTTAG', 'CGGCAACAGC', 'AATGCTGGCA', 'ACTGATGTGC', 'TATACTATCT', 'AAATTCTTTC', 'CAACGGTGAC', 'TACCAAGTAA', 'GAAGATTGTA', 'ACCCTTGAGT', 'TTACGGCTAA', 'ACATACACCC', 'CTTGGTTCCT', 'GAGTATGTAC', 'AAATTTGTGC'], read_lengths=[14, 73, 10, 70, 11, 11, 86, 88, 71, 66, 64, 61, 9, 10, 13, 72, 84, 86, 74, 69, 76, 68, 66, 68, 60, 48, 49, 48, 50, 46, 49, 10, 48, 48, 53, 49, 49, 48, 46, 46, 47, 45, 61, 48, 10, 10, 10, 48, 49, 48, 49, 48, 43, 50, 49, 48, 48, 51, 48, 50, 46, 50, 49, 62, 42, 50, 49, 51, 48, 50, 49, 48, 48, 46, 10], utr_sizes_from_reads=[1133, 545, 472, 1165, 1090, 902, 544, 545, 514, 505, 500, 490, 1118, 733, 740, 528, 540, 529, 515, 522, 519, 509, 503, 505, 491, 1255, 1255, 1158, 1159, 1148, 877, 589, 501, 512, 510, 507, 501, 498, 492, 494, 497, 470, 315, 1407, 1366, 1366, 1366, 1156, 1161, 1157, 1148, 862, 845, 521, 519, 515, 512, 522, 512, 515, 497, 517, 516, 526, 500, 506, 499, 504, 501, 502, 502, 497, 499, 496, 204]),
 MappedReadInformation(utr_name='ENSMUSG00000025902', read_start_positions=[4490978, 4490984, 4491438, 4490990, 4490992, 4491066, 4491434, 4491432, 4491652, 4490986, 4491434, 4491615, 4491035, 4491078, 4491078, 4491370, 4491523, 4491635, 4491708, 4491713, 4491713, 4490990, 4490990, 4491436, 4491002, 4491436, 4491436, 4491448, 4491078, 4491251, 4491263, 4491329, 4491333, 4491455, 4491436, 4491443, 4490974, 4490974, 4491446, 4490984, 4490985, 4491261, 4491434, 4490990, 4490959, 4491110, 4491189, 4491322, 4491370, 4491370, 4491370, 4491370, 4491370, 4491370, 4491370, 4491370, 4491370, 4491452, 4491434, 4491440, 4491437, 4491436, 4491439, 4491437, 4491442, 4491438, 4491445, 4491438, 4491436, 4491439, 4491446, 4491456, 4491519, 4491519, 4491709, 4491708, 4491708, 4491708, 4491708], read_strands=['+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+'], read_barcodes=['AGTAGTCGTAACGCGA-1', 'TTCGAAGGTTAAGGGC-1', 'TTCGAAGGTTAAGGGC-1', 'GGGTCTGTCACAGGCC-1', 'GGGTTTGTCACAGGCC-1', 'GGGCACTAGGGCATGT-1', 'CGTTCTGGTGAGGGTT-1', 'CTGAAACGTCTCCACT-1', 'GGTGTTAGTAACGACG-2', 'ATTTCTGAGCAATAGT-3', 'TCCGAAACAGTGAGCA-3', 'CTCCAACAGAAGTATC-3', 'GTGCACGTCCTACCGT-4', 'GGTGTCGAGGAGGCAG-4', 'GGTGTCGAGCAGATAT-4', 'CGATGCGAGTAGAGTT-4', 'CCACGAGTCAATCTCT-4', 'CACTTCGCATCGATCA-4', 'GCAACCGTCGCTACGG-4', 'CGTCAAATCACCGACG-4', 'CGTCAAATCACCGACG-4', 'AGGCATTCAGACAAGC-5', 'AGGCATTCAGACAAGC-5', 'AGGCATTCAGACAAGC-5', 'CCCTAACAGCTGACAG-5', 'CCCTAACAGCTGACAG-5', 'CCCTAACAGCTGACAG-5', 'CCCTAACAGCTGACAG-5', 'GGTGTCGAGCCTCAGC-5', 'ACGTAGTAGCAGTACG-5', 'TCATGAGAGAGGATCC-5', 'AAACGCTGTTTAAGGA-5', 'TTGCTGCTCAAACGAA-5', 'GAGATGGTCGTGACTA-5', 'TCCTAACAGCTGACAG-5', 'AGTTCGAGTTGCATTG-5', 'GATCCCTGTGACACGA-6', 'TACCCGTTCTGAGGCC-6', 'TACCCGTTCTGAGGCC-6', 'GCGATCGAGACCATGG-6', 'CGTAGTAAGAATAACC-6', 'CGTAGTAAGAATAACC-6', 'CGTAGTAAGAATAACC-6', 'AGGAATAGTGAGCGAT-6', 'CTCAACCCAAGGCAAC-6', 'TCACGCTCAAGTCGTT-6', 'GACATCATCGAACGGA-6', 'TACTTACTCTTGATTC-6', 'CGATGCGAGAGATGCC-6', 'CGATGCGAGAGATGCC-6', 'CGATGCGAGAGATGCC-6', 'CGATGCGAGAGATGCC-6', 'CGATGCGAGAGATGCC-6', 'CGATGCGAGAGATGCC-6', 'CGATGCGAGAGATGCC-6', 'CGATGCGAGAGATGCC-6', 'CGATGCGAGCTGGCTC-6', 'AGACTCATCGTAGTCA-6', 'AGACTCATCGTAGTCA-6', 'GGTGATTGTAGGTGCA-6', 'TGTCCACGTCCGGCAT-6', 'ATTCCATGTGACAGGT-6', 'AGAAGCGGTGAATATG-6', 'AGAAGCGGTGAATATG-6', 'TGCAGATTCTGCGTCT-6', 'GTTACGAGTACCATAC-6', 'TTACCATGTCATTCCC-6', 'AGTAGCTCAAGAGGTC-6', 'GGACTCATCGTAGTCA-6', 'CAGATCATCCGGCAGT-6', 'CTGATCATCCGGCAGT-6', 'TGTGTGGCAAATACGA-6', 'GGAGCAAGTCCTGGTT-6', 'GGAGCAAGTCCTGGTG-6', 'GCGAGAATCGAGTTGT-6', 'GCAACCGTCCTGCTAC-6', 'GCAACCGTCCTGCTAC-6', 'GCAACCGTCCTGCTAC-6', 'GCAACCGTCTCTTCAA-6'], read_umis=['GCATCATAGG', 'GCACACTGGC', 'ATGATTACGT', 'CTAAACGCAA', 'CTAAACGCAA', 'CGGACGGAAA', 'TTGGCCAAAT', 'GTAGTCCGGG', 'CTAAGGATGG', 'CATTTCTTAA', 'AGCGCACGAA', 'GTTCTATTAC', 'TCTTTGGGCT', 'ATGGTGAGTC', 'AATAAGCCGC', 'TTGCGTGTTT', 'GTATCCCCTC', 'ATCCAGTCTA', 'AATAGGGTCA', 'CTTTCAGGTC', 'ATCGATATCT', 'ATGTTGTTAC', 'CGCGGGAGTA', 'AAAGCCCACA', 'ACTATTTTCT', 'GATAAGGTCT', 'TGCTCTGATC', 'GCGGCTCTCG', 'AGTCTTATAG', 'CGTAAATAAA', 'CGGGTCAAAT', 'CCTGCCAGTA', 'GGTATACACT', 'TCTATAACCC', 'TGCTCTGATC', 'GCGTGTACTT', 'AACGCTAGTA', 'GCACTCGTTC', 'AATGGTGTAT', 'TTTTAGGATA', 'TCCTTGAACT', 'GCTGAGTTCA', 'CATCCTGGAC', 'CGAGTTACTA', 'TTTATTTTGA', 'CCATGAACAG', 'ATGTACATAA', 'CCCAGCTTTG', 'ATGGTCTGGA', 'AAGTTGACCT', 'AAGGCAACAA', 'TGTGGTACCA', 'CGGGCCTTTT', 'CCCCAGACCT', 'CGTATGTACT', 'TGAATCCCTT', 'ACCGATATCC', 'GCTTAACCAG', 'AGTCTTAGGA', 'AATGTTAAAG', 'GTCATAGACA', 'TTTAAATATA', 'TGAAAAACTA', 'CGTGACTCGG', 'CCCATGCAAA', 'TACCATGCAG', 'CAAACTGTTG', 'CATTTTACTC', 'AGTCTTAGGA', 'GATAAACTAC', 'GATAAACTAC', 'CCGGCATGTA', 'TGACGTCTGT', 'AATTAATATT', 'TGGAATTCTA', 'TTACAAGATG', 'GGTTTCCTTT', 'AACCTACTGA', 'CCAACATTAA'], read_lengths=[26, 48, 44, 44, 42, 14, 48, 52, 12, 59, 63, 19, 17, 9, 9, 9, 9, 17, 9, 8, 8, 41, 42, 48, 49, 48, 46, 46, 9, 13, 28, 72, 20, 28, 47, 40, 50, 50, 44, 47, 46, 50, 48, 42, 18, 71, 14, 14, 13, 13, 13, 13, 13, 13, 13, 13, 9, 38, 45, 46, 45, 46, 44, 46, 41, 45, 36, 46, 47, 44, 45, 37, 11, 11, 11, 9, 9, 9, 9], utr_sizes_from_reads=[736, 730, 276, 724, 722, 648, 280, 282, 62, 728, 280, 99, 679, 636, 636, 344, 191, 79, 6, 1, 1, 724, 724, 278, 712, 278, 278, 266, 636, 463, 451, 385, 381, 259, 278, 271, 740, 740, 268, 730, 729, 453, 280, 724, 755, 604, 525, 392, 344, 344, 344, 344, 344, 344, 344, 344, 344, 262, 280, 274, 277, 278, 275, 277, 272, 276, 269, 276, 278, 275, 268, 258, 195, 195, 5, 6, 6, 6, 6])]

In [3]:
len(wt_test[:20])

20

In [4]:
for utr in wt_test:
    print(utr)
    break

MappedReadInformation(utr_name='ENSMUSG00000051951', read_start_positions=[3214887, 3215475, 3215548, 3214855, 3214930, 3215118, 3215476, 3215475, 3215506, 3215515, 3215520, 3215530, 3214902, 3215287, 3215280, 3215492, 3215480, 3215491, 3215505, 3215498, 3215501, 3215511, 3215517, 3215515, 3215529, 3214765, 3214765, 3214862, 3214861, 3214872, 3215143, 3215431, 3215519, 3215508, 3215510, 3215513, 3215519, 3215522, 3215528, 3215526, 3215523, 3215550, 3215705, 3214613, 3214654, 3214654, 3214654, 3214864, 3214859, 3214863, 3214872, 3215158, 3215175, 3215499, 3215501, 3215505, 3215508, 3215498, 3215508, 3215505, 3215523, 3215503, 3215504, 3215494, 3215520, 3215514, 3215521, 3215516, 3215519, 3215518, 3215518, 3215523, 3215521, 3215524, 3215816], read_strands=['+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+'], read_barcodes=['TCAGCTCCACTGAAGG-1', 'AAGCCGCGTGAAGGCT-2', 'GGACATTAGAAGAAGC-2', 'CTTAGGACACCTCAGG-3', 'AGGTGTTTCCTTCAGC-3', 'TTCTTGACAGCTGCCA-3', 'GACTTCCAGCTATCTG-3', 'TGACAGTTCTTACGGA-3', 'ATTCCCGCACTTCATT-3', 'ACGTACAAGTACTGGG-3', 'ACGTACAAGTACTGGG-3', 'CGGGCATAGCCTTTCC-3', 'GCACGTGGTGACTCGC-4', 'AATGAAGCAGACCCGT-4', 'CATCCCATCAAAGGAT-4', 'TCCTCTTAGTGGTTAA-4', 'TTCATTGAGTCATTGC-4', 'TTCATTGAGTCATTGC-4', 'CTGCTCAAGCAAGTCG-4', 'ATTCCCGAGATTTGCC-4', 'GGGTATTCAGTTAAAG-4', 'GTCAAACCAATTTCGG-4', 'CGCATAATCACCGCTT-4', 'TGACAGTAGATTTGCC-4', 'TACTTGTGTCAAGGCA-4', 'AATGAAGTCCGCGAGT-5', 'TGCGACGTCGGTAGAG-5', 'TATTGGGCAGAGATGC-5', 'ACGGTTACAGAGACTG-5', 'ANGGTTACAGAGACTG-5', 'ATCACTTGTGGCACTC-5', 'AGGAAATCACTAGTAC-5', 'ATCACTTGTCTGCCTT-5', 'GGTGAAGCACAGCCAC-5', 'TTCCAATCAGTATGAA-5', 'TCTGGCTTCACCTACC-5', 'AACGGGAGTTTACCTT-5', 'CTCTCGATCGCTGTCT-5', 'GTGGTTATCAGTGATC-5', 'TTAATCCAGCACTCCG-5', 'ATGATCGCAGTGTGCC-5', 'GACATCAGTTAAACCC-5', 'CAAAACTTAGTAAAAC-5', 'GACTCTCTCACAGTGT-6', 'TCAAGCAGTCGAATTC-6', 'TCAAGCAGTCGAATTC-6', 'TCAAGCAGTCGAATTC-6', 'CTGCAGGGTTAGAAAC-6', 'GCAGGCTAGCGAACTG-6', 'ACACTGATCCGAAATC-6', 'AAGACAATCTAGCCAA-6', 'CCATAAGTCGGTATGT-6', 'CTTCTCTTCTGCAGCG-6', 'TCCACGTGTGGCCTCA-6', 'AGACAGGTCGACATCA-6', 'AAGTACCCACATTCTT-6', 'CTCCGATGTGTCATCA-6', 'ACTTAGGGTTACACAC-6', 'TGTGGCGCAGTTCCAA-6', 'GTTCGCTCAATGTCAC-6', 'CCTTTGGTCTACGCAA-6', 'TCATTCAGTCCGGACT-6', 'TCCTCGAGTTAGTCGT-6', 'GTGTCCTAGTGGCCTC-6', 'TCTACCGCACCTGCAG-6', 'AGCCAATAGCTACGTT-6', 'AGCCAATAGCTACGTT-6', 'AATCACGTCCAGCTCT-6', 'CTTGAGAAGTCAGAGC-6', 'TATCCTACATCGAGCC-6', 'TCCACCACAGACTCTA-6', 'TCTATACCAAGTATAG-6', 'ACAAGCTGTAGTCCTA-6', 'ATGATCGCAGTGTGCC-6', 'CAACAGTCATCCCACT-6'], read_umis=['GAGGGGACAC', 'TAGCCCAGTC', 'TCTTATGATC', 'AACCCTCTGT', 'TTAATTAAAG', 'TAATTTCTCA', 'AGGCGAATGC', 'CGCTATGAAG', 'ATCGTTATGT', 'TTCCACTGGG', 'GGTGAGTTCA', 'GTTGTCAACT', 'GCGTGTATTT', 'AGTAGTAGAT', 'ATGACCCTCT', 'AAGTCGATGA', 'GAGGCACGTA', 'TATTTTGCAC', 'CCTTTTTATG', 'TCATCCACTG', 'GTAAGGCGAT', 'TGGGTTTCTA', 'TTTCTCGACT', 'ACCTTCAATG', 'TGCAATATCA', 'GTGATTCGTA', 'TTACCTCAGC', 'CCGGACCTTT', 'TGGACGGCTC', 'TGGACGGCTC', 'ATTTGCTTTA', 'CACAGATCTG', 'TACTGATCTA', 'CCAGACACTC', 'TTCTGTCTAG', 'CGAAAGTATA', 'CTTTGGCTAG', 'TAACATCAGG', 'AGTTTCGTAG', 'CTTGGACAAG', 'GAGTATGTAC', 'TTGGCCAAAA', 'CCATCAAAAT', 'TCAGTACCAC', 'TATTTCAGTC', 'TAATCTTCTA', 'CCAACTTTAA', 'CCCAAAATAA', 'TTGTAGATTA', 'ACACGCTATC', 'GATAATCATT', 'TAATTCTTTT', 'TTCCTAACTT', 'AAATTCCGAT', 'ACTTTTCCCC', 'TTGAAAAGGG', 'TCCAAACCGT', 'GAGACGCATG', 'CCTTTCGTGC', 'TCGCGCTGGG', 'TTATCTTTAG', 'CGGCAACAGC', 'AATGCTGGCA', 'ACTGATGTGC', 'TATACTATCT', 'AAATTCTTTC', 'CAACGGTGAC', 'TACCAAGTAA', 'GAAGATTGTA', 'ACCCTTGAGT', 'TTACGGCTAA', 'ACATACACCC', 'CTTGGTTCCT', 'GAGTATGTAC', 'AAATTTGTGC'], read_lengths=[14, 73, 10, 70, 11, 11, 86, 88, 71, 66, 64, 61, 9, 10, 13, 72, 84, 86, 74, 69, 76, 68, 66, 68, 60, 48, 49, 48, 50, 46, 49, 10, 48, 48, 53, 49, 49, 48, 46, 46, 47, 45, 61, 48, 10, 10, 10, 48, 49, 48, 49, 48, 43, 50, 49, 48, 48, 51, 48, 50, 46, 50, 49, 62, 42, 50, 49, 51, 48, 50, 49, 48, 48, 46, 10], utr_sizes_from_reads=[1133, 545, 472, 1165, 1090, 902, 544, 545, 514, 505, 500, 490, 1118, 733, 740, 528, 540, 529, 515, 522, 519, 509, 503, 505, 491, 1255, 1255, 1158, 1159, 1148, 877, 589, 501, 512, 510, 507, 501, 498, 492, 494, 497, 470, 315, 1407, 1366, 1366, 1366, 1156, 1161, 1157, 1148, 862, 845, 521, 519, 515, 512, 522, 512, 515, 497, 517, 516, 526, 500, 506, 499, 504, 501, 502, 502, 497, 499, 496, 204])

In [24]:
data = pd.DataFrame.from_dict(wt_test.__dict__)

In [25]:
data.head()

,utr_ids,_index,read_start_positions,read_strands,read_barcodes,read_umis,read_lengths,utr_sizes_from_reads,ENSMUSG00000051951,ENSMUSG00000025902,...,ENSMUSG00000068457_10,ENSMUSG00000068457_11,ENSMUSG00000068457_13,ENSMUSG00000068457_23,ENSMUSG00000069045,ENSMUSG00000069045_3,ENSMUSG00000069045_5,ENSMUSG00000069045_8,ENSMUSG00000069045_10,ENSMUSG00000069045_11
0,ENSMUSG00000051951,0,"[3214887, 3215475, 3215548, 3214855, 3214930, ...","[+, +, +, +, +, +, +, +, +, +, +, +, +, +, +, ...","[TCAGCTCCACTGAAGG-1, AAGCCGCGTGAAGGCT-2, GGACA...","[GAGGGGACAC, TAGCCCAGTC, TCTTATGATC, AACCCTCTG...","[14, 73, 10, 70, 11, 11, 86, 88, 71, 66, 64, 6...","[1133, 545, 472, 1165, 1090, 902, 544, 545, 51...",MappedReadInformation(utr_name='ENSMUSG0000005...,MappedReadInformation(utr_name='ENSMUSG0000002...,...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...
1,ENSMUSG00000025902,0,"[4490978, 4490984, 4491438, 4490990, 4490992, ...","[+, +, +, +, +, +, +, +, +, +, +, +, +, +, +, ...","[AGTAGTCGTAACGCGA-1, TTCGAAGGTTAAGGGC-1, TTCGA...","[GCATCATAGG, GCACACTGGC, ATGATTACGT, CTAAACGCA...","[26, 48, 44, 44, 42, 14, 48, 52, 12, 59, 63, 1...","[736, 730, 276, 724, 722, 648, 280, 282, 62, 7...",MappedReadInformation(utr_name='ENSMUSG0000005...,MappedReadInformation(utr_name='ENSMUSG0000002...,...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...
2,ENSMUSG00000033845,0,"[4773251, 4773249, 4776424, 4776448, 4773257, ...","[+, +, +, +, +, +, +, +, +, +, +, +, +, +, +, ...","[CCTAGCTTCCACGAAT-1, CGTTGGGGTACTCGCG-1, CGTTG...","[CGCACCCCGG, TAAGGTTTTT, GGGAAGTTAT, GAAGACGGT...","[47, 49, 48, 28, 50, 52, 53, 45, 42, 48, 53, 4...","[3211, 3213, 38, 14, 3205, 3208, 3210, 1990, 2...",MappedReadInformation(utr_name='ENSMUSG0000005...,MappedReadInformation(utr_name='ENSMUSG0000002...,...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...
3,ENSMUSG00000033845_2,0,"[4777604, 4777617, 4777616, 4777629, 4777614, ...","[+, +, +, +, +, +, +, +, +, +, +, +, +, +, +, ...","[AGCTGCACTTCAATAT-1, CCCATACCAAGAAAGG-2, AGAGT...","[TAATTTTTGC, GTCAGATGCA, TCCGAGCGGA, CTTATTATT...","[101, 52, 54, 10, 68, 70, 64, 69, 64, 63, 59, ...","[43, 30, 32, 18, 33, 35, 26, 34, 30, 20, 12, 1...",MappedReadInformation(utr_name='ENSMUSG0000005...,MappedReadInformation(utr_name='ENSMUSG0000002...,...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...
4,ENSMUSG00000033845_3,0,"[4781307, 4781436, 4781443, 4781442, 4781443, ...","[+, +, +, +, +, +, +, +, +, +, +, +, +, +, +, ...","[CATATTCTCACGGTTA-1, GTCGGGTTCTGTACGA-1, ACGCA...","[GGTTGGTGGA, CACGGCTGGC, GTAAGAGTAT, TCGACAAAA...","[43, 14, 11, 12, 11, 12, 41, 47, 50, 49, 50, 5...","[912, 783, 776, 777, 776, 777, 773, 778, 780, ...",MappedReadInformation(utr_name='ENSMUSG0000005...,MappedReadInformation(utr_name='ENSMUSG0000002...,...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...

In [39]:
data.shape[0]/5

4438.0

In [42]:
data.shape[0]/4438

5.0

In [48]:
S = 4438
N = int(data.shape[0]/4438)
frames = [data.iloc[i*S:(i+1)*S].copy() for i in range(N)]

In [54]:
frames[4]

,utr_ids,_index,read_start_positions,read_strands,read_barcodes,read_umis,read_lengths,utr_sizes_from_reads,ENSMUSG00000051951,ENSMUSG00000025902,...,ENSMUSG00000068457_10,ENSMUSG00000068457_11,ENSMUSG00000068457_13,ENSMUSG00000068457_23,ENSMUSG00000069045,ENSMUSG00000069045_3,ENSMUSG00000069045_5,ENSMUSG00000069045_8,ENSMUSG00000069045_10,ENSMUSG00000069045_11
17752,ENSMUSG00000006315,0,"[30727748, 30727751, 30727756, 30727756, 30727...","[+, +, +, +, +, +, +, +, +, +, +, +, +, +, +, ...","[ACGATGTGTATCACCA-1, TTGACTTAGTGCCAGA-1, GCTTC...","[GCTCAAGAGG, CTTTCTCTAG, CACCGGCACC, GCCGGGTCA...","[45, 48, 44, 45, 47, 48, 48, 43, 47, 47, 49, 4...","[154, 151, 146, 146, 148, 147, 147, 142, 144, ...",MappedReadInformation(utr_name='ENSMUSG0000005...,MappedReadInformation(utr_name='ENSMUSG0000002...,...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...
17753,ENSMUSG00000006315_4,0,"[30728465, 30728475, 30728497, 30728551, 30728...","[+, +, +, +, +, +, +, +, +, +, +, +, +, +, +, ...","[GGGCAGCAACCATAAT-1, CATAATCTTGTACTCC-1, CCTGC...","[CTTGTACTCC, CCCTTGTCTG, TGACAAGGTT, ACTATACGT...","[101, 101, 101, 52, 46, 58, 15, 9, 9, 101, 48,...","[102, 92, 70, 16, 7, 30, 24, 66, 66, 128, 112,...",MappedReadInformation(utr_name='ENSMUSG0000005...,MappedReadInformation(utr_name='ENSMUSG0000002...,...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...
17754,ENSMUSG00000061099,0,"[30729775, 30729871, 30729879, 30729953, 30729...","[+, +, +, +, +, +, +, +, +, +, +, +, +, +, +, ...","[GCATACACAGCTGTGC-1, GTGCTTCTCGCGATCG-1, CGTTA...","[GCATTCACGG, GTCTAACGAC, GTTTGGGACT, CAATTGATT...","[36, 14, 10, 7, 8, 40, 46, 48, 101, 101, 49, 9...","[183, 87, 79, 5, 5, 122, 128, 126, 173, 172, 1...",MappedReadInformation(utr_name='ENSMUSG0000005...,MappedReadInformation(utr_name='ENSMUSG0000002...,...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...
17755,ENSMUSG00000046056,0,"[30756131, 30756133, 30756120, 30756124, 30756...","[-, -, -, -, -, -, -, -, -, -, -, -, -, -, -, ...","[GACCAATTCGGCTTGG-1, GACCAATTCGGCTTGG-1, TCAGC...","[CCCGTACAGG, ATCAGCGGTA, CCTTGTGCGG, CGAGTATAC...","[49, 49, 46, 47, 47, 48, 46, 23, 46, 44, 44, 4...","[143, 145, 132, 136, 139, 137, 135, 112, 144, ...",MappedReadInformation(utr_name='ENSMUSG0000005...,MappedReadInformation(utr_name='ENSMUSG0000002...,...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...
17756,ENSMUSG00000060962,0,"[30780894, 30781053, 30781060, 30781060, 30781...","[-, -, -, -, -, -, -, -, -, -, -, -, -, -, -, ...","[CACATAGTCTTCATGT-1, TAAGTGCCACTCTGTC-1, GGACA...","[ATAAGAGCGA, GGGGGGTCTA, ACCCCTGTAT, ATTCCAAGA...","[13, 46, 44, 43, 47, 45, 48, 42, 46, 35, 44, 4...","[155, 314, 321, 321, 322, 316, 324, 323, 323, ...",MappedReadInformation(utr_name='ENSMUSG0000005...,MappedReadInformation(utr_name='ENSMUSG0000002...,...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22185,ENSMUSG00000069045_3,0,"[1263841, 1263915, 1263918, 1263944, 1263942, ...","[+, +, +, +, +, +, +, +, +, +, +, +, +]","[GCACTCTGCGTTGATA-1, AAATTCCTCTCATTGA-2, TTCCT...","[CCACTGCTTT, AAAAAGAGGT, AAGAGGTGGC, TTCCTCTCA...","[77, 101, 115, 51, 51, 54, 11, 47, 52, 53, 53,...","[107, 33, 30, 4, 6, 10, 113, 47, 8, 4, 5, 0, 0]",MappedReadInformation(utr_name='ENSMUSG0000005...,MappedReadInformation(utr_name='ENSMUSG0000002...,...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...
22186,ENSMUSG00000069045_5,0,"[1265103, 1265103, 1265091, 1265179, 1265169, ...","[+, +, +, +, +, +, +, +, +, +, +, +, +, +, +, ...","[CTCCTAGATCTGTCTC-1, CTCCTAGATCCGTCTC-1, TTCTG...","[CATGAATACT, CATGAATACT, CATGAATACT, TTATATCGT...","[95, 95, 101, 53, 19, 114, 110, 61, 63, 39, 20...","[105, 105, 117, 29, 39, 115, 110, 63, 59, 106,...",MappedReadInformation(utr_name='ENSMUSG0000005...,MappedReadInformation(utr_name='ENSMUSG0000002...,...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...
22187,ENSMUSG00000069045_8,0,"[1266415, 1266421, 1266422, 1266420, 1266421, ...","[+, +, +, +, +, +, +, +, +, +, +, +, +, +, +, ...","[TTCTACAGTTAAAGAC-1, CTCGTACCACATCCGG-1, CGTGA...","[TCACAAAGCT, GCCCAGGGCG, CCGTACAGTT, CGAGGCCGC...","[63, 59, 58, 59, 59, 58, 55, 56, 56, 55, 60, 9...","[103, 97, 96, 98, 97, 96, 96, 94, 94, 95, 98, ...",MappedReadInformation(utr_name='ENSMUSG0000005...,MappedReadInformation(utr_name='ENSMUSG0000002...,...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...
22188,ENSMUSG00000069045_10,0,"[1267152, 1267154, 1267164, 1267163, 1267161, ...","[+, +, +, +, +, +, +, +, +, +, +, +, +, +, +, ...","[AGCGGTCTCGCAAGCC-1, ACTGAGTCACGTCAGC-1, AGGGT...","[CACAACCTTT, AGTAAGAAGT, GCCAATTGAT, AAAACCCCC...","[50, 48, 45, 47, 50, 76, 46, 51, 45, 96, 47, 6...","[35, 33, 23, 24, 26, 8, 31, 36, 30, 77, 21, 30...",MappedReadInformation(utr_name='ENSMUSG0000005...,MappedReadInformation(utr_name='ENSMUSG0000002...,...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...
22189,ENSMUSG00000069045_11,0,"[1269730, 1269766, 1269774, 1269769, 1269768, ...","[+, +, +, +, +, +, +, +, +, +, +, +, +, +, +, ...","[TTAGGACAGTAGGCCA-1, CGAATGTTCCGAGCCA-1, GCTTG...","[TTAAGTCCCT, GCTATAGATT, TAAGAGACTG, GTTTTTAAA...","[23, 66, 58, 63, 64, 51, 68, 62, 63, 58, 64, 6...","[109, 73, 65, 70, 71, 59, 74, 70, 70, 65, 70, ...",MappedReadInformation(utr_name='ENSMUSG0000005...,MappedReadInformation(utr_name='ENSMUSG0000002...,...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...,MappedReadInformation(utr_name='ENSMUSG0000006...

In [50]:
len(frames)

5